### ISSUE TITLE
Feature Request - Support for Cluster

### ISSUE THREAD

**Issue by HardikLohogaonkar** [Esri/arcgis-runtime-samples-android#1005]
Hi team, can you provide Cluster Support for Android SDK. There is a thread on official community in that you have mentioned about this feature is present in your future releases. It's a long time pending request.

**Comment by TADraeseke** [comment]
Hi Hardik. Looks like [the request is still open here](https://community.esri.com/t5/arcgis-runtime-sdk-for-android-questions/cluster-rendering/m-p/77585). I'd recommend adding your post there.

We try to reserve the issue backlog here specifically for bugs or problems with the samples in particular.
