### ISSUE TITLE
geojson数据无法加载问题

### ISSUE THREAD

**Issue by Graves-nanqiang** [Esri/arcgis-runtime-samples-android#1011]
geojson格式的数据无法加载出来，使用的是FeatureCollection.fromJson这个方法，但一直无法加载数据。
以下的部分数据:
{"type":"FeatureCollection","crs":{"type":"name","properties":{"name":"EPSG:4326"}},"features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[115.85301011962133,28.685312910262667]},"properties":{"NAME":"测试点"}}]}

**Comment by TADraeseke** [comment]
Hi there! We try to use the repo to just answer questions or address issues with samples. If you have a more general question please ask it here:

https://community.esri.com/t5/arcgis-runtime-sdk-for-android-questions/bd-p/arcgis-runtime-sdk-for-android-questions

Thanks!
