### ISSUE TITLE
ExportTileCacheTask doesn't work with World Imagery service

### ISSUE THREAD

**Issue by gkarpiak** [Esri/arcgis-runtime-samples-android#102]
When changing tile service url in ExportTileCacheTask sample:
<string name="tileServiceURL">http://sampleserver6.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer</string>

to:
<string name="tileServiceURL">http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer</string>

Example stops working: It displays toast "FAILED", then "TileCache successfully downloaded", but map is empty.

It would help a lot if some information on that could be added to the README file.

**Comment by doneill** [comment]
@gkarpiak The ExportTileCache sample hard codes the level of detail expected in the sample service url so in order to work with other services you will have to edit the source of the sample to retrofit the level of details in the service you want to work with.  I reference some of the code below: 

```java
final CharSequence[] items = { "Level ID:0", "Level ID:1", "Level ID:2",
		"Level ID:3", "Level ID:4", "Level ID:5", "Level ID:6",
		"Level ID:7", "Level ID:8", "Level ID:9", };

double[] mapResolution = { 156543.03392800014, 78271.51696399994,
		39135.75848200009, 19567.87924099992, 9783.93962049996,
		4891.96981024998, 2445.98490512499, 1222.992452562495,
		611.4962262813797, 305.74811314055756 };
```

**Comment by doneill** [comment]
@gkarpiak Did the comment above resolve your issue?  Would you still like more doc about changing services or how the levels work?  Please let us know so we can triage the issue appropriately.

**Comment by gkarpiak** [comment]
@doneill thanks for spending your time. It's not an issue anymore. (I did a research using Esri and not using that at the moment.)
