### ISSUE TITLE
Geometry editing problems 

### ISSUE THREAD

**Issue by Desalegn21** [Esri/arcgis-runtime-samples-android#105]
Hi guys, while I edit geometry and if there new feature teaches or near the edited, the first edited is removed but new edited feature appear on its place, is there any help.

**Comment by doneill** [comment]
@Desalegn21 Which sample are you referencing with this question? I am not able to reproduce your issue with the [Geometry Editor sample](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/GeometryEditor).  Please provide more information on how to reproduce the issue you are having and with which specific sample.

**Comment by Desalegn21** [comment]
it was of offlineEditor,i  solved myself .That was tolerance problem
