### ISSUE TITLE
Quartz Beta - Custom TileSource

### ISSUE THREAD

**Issue by snodnipper** [Esri/arcgis-runtime-samples-android#111]
It would be great if we could have an example of using the ImageTiledLayer and extending getTileAsync to provide our own tiles.

For example, a custom adapter to one of the following would be great for a demo:
http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/11/686/1016
http://a.tile.openstreetmap.org/10/536/358.png

``` java
public class MyTilesService extends ImageTiledLayer {

    protected MyTilesService(Context context, CoreImageTiledLayer coreImageTiledLayer) {
        super(coreImageTiledLayer);
    }

    @Override
    protected ListenableFuture<byte[]> getTileAsync(final TileKey tileKey) {
    ...custom
```

Perhaps you can comment as to whether it is even possible right now for non ArcGISMapImageLayers?  I had some amazing blow-ups today when using:

`CoreImageTiledLayer coreImageTiledLayer = CoreImageTiledLayer.b(123456789L);`

For example:

```
Caused by: java.lang.IllegalArgumentException: Parameter pendingRequest or future or owningCollection must not be null
at com.esri.arcgisruntime.internal.requestable.a.<init>(SourceFile:88)
at com.esri.arcgisruntime.layers.Layer$1.a(SourceFile:63)
at com.esri.arcgisruntime.internal.jni.CoreLayer.onRequestRequired(SourceFile:486)
at com.esri.arcgisruntime.internal.jni.CoreMapView.nativeSetMap(Native Method)
at com.esri.arcgisruntime.internal.jni.CoreMapView.a(SourceFile:154)
at com.esri.arcgisruntime.internal.mapping.view.g.a(SourceFile:522)
at com.esri.arcgisruntime.mapping.view.MapView.setMap(SourceFile:494)
```

**Comment by willcrick** [comment]
Does this help?
https://github.com/Esri/arcgis-runtime-samples-android/tree/master/LocalMBTiles

Its local tiles, but it adheres to the same pattern.

**Comment by osedok** [comment]
In terms of the tile services following openstreetmap convention for the tiles you may also have a look at OpenStreetMapLayer class: https://developers.arcgis.com/android/api-reference/reference/com/esri/android/map/osm/OpenStreetMapLayer.html

**Comment by snodnipper** [comment]
Thanks @willcrick / @osedok.  I am specifically referring to the latest Quartz SDK (sadly your references are for the stable release).

**Comment by willcrick** [comment]
Ah ok, sorry, i should have read the title :smile: 
So far no samples for that based on Quartz, sorry. We do have plans to add it down the line though.

**Comment by osedok** [comment]
As far as I can see "Specialized layers are not available at this beta release of the software. They will include KML, Web Map Service layers, Message Group Layers, BingMaps Layer and Open Street Map layer, for example..." Source: https://developers.arcgis.com/android/beta/guide/layer-types.htm#ESRI_SECTION1_A3FEE04544B14DEE8061642A3EE8BC47

**Comment by osedok** [comment]
@snodnipper - I have tried to extend ImageTiledLayer as well, but run into the same exception as you...

**Comment by willcrick** [comment]
We did not explicitly expose the ability to do this in Quartz Beta 1, its something for a future release.

**Comment by imshz** [comment]
Hi, I cant see this is possible now that the version 100 is released. Is support for this feature planned in any near releases? It would be realy nice to provide own tiles as well as use the built in layertypes.

**Comment by pengfei666** [comment]
I believe it is supported now. Find the latest API doc.
