### ISSUE TITLE
Help !! Problem while executing project 

### ISSUE THREAD

**Issue by zahrouni** [Esri/arcgis-runtime-samples-android#116]
Hello, the fellowing error message had shown during the test .. and i don't why and where it came from ... could you help me please ?? ..

` Could not find method android.content.res.Resources.getDrawable, referenced from method com.esri.arcgisruntime.internal.mapping.view.a.a`

**Comment by doneill** [comment]
@zahrouni Please excuse the delay, but have you resolved this issue?  If not, what sample are you trying to run?  And please detail the steps you are doing to get this error.

**Comment by doneill** [comment]
Closing,  @zahrouni please re-open if applicable.
