### ISSUE TITLE
Move a point or update coordinates

### ISSUE THREAD

**Issue by ahmetakdogan** [Esri/arcgis-runtime-samples-android#120]
I want to move a point or update coordinates of a point or polyline. How can I do?

**Comment by shellygill** [comment]
This is quite a general question, and the answer would depend on may things, for example where your geometry is from, and how you want to make the changes. You might find the https://github.com/Esri/arcgis-runtime-samples-android/tree/master/GeometryEditor sample relevant. 

For general questions like this about how to develop with the ArcGIS Runtime SDK for Android, the best place to ask is on the geonet forum at https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android. This repo is for the samples in particular, so if you have any problems or suggestions for working with the samples in this repo, that's when you should add an issue here.

Closing as geonet question.
