### ISSUE TITLE
Query cloud feature service sample needs update to service URL and field name

### ISSUE THREAD

**Issue by shellygill** [Esri/arcgis-runtime-samples-android#134]
New hosted service URL for this sample should be http://www.arcgis.com/home/item.html?id=6996f03a1b364dbab4008d99380370ed

New field name for attribute query should be 'CNTRY_NAME'

**Comment by doneill** [comment]
@shellygill PR #136 is ready for you to review as a fix for this issue.

**Comment by doneill** [comment]
Verified fixed
