### ISSUE TITLE
Quartz beta: encoding error in geocoding results

### ISSUE THREAD

**Issue by mlumeau** [Esri/arcgis-runtime-samples-android#151]
When getting a reverse geocoding result, the `getLabel()` method of `GeocodeResult`returns a broken string as below:

> 27 Avenue des Champs-�lys�es, 75008, 8e Arrondissement, Paris, �le-de-France

As far as I know, the string charset is UTF-8. It still appears broken in an Android `TextView`.

**Comment by doneill** [comment]
@mlumeau Thanks for bringing our attention to this.  We have an existing internal bug in our Android SDK and are actively working to resolve this.

**Comment by doneill** [comment]
@mlumeau This issue has been fixed and will be in the Quartz final release.

**Comment by doneill** [comment]
@mlumeau Can you verify the fix from the released samples?

**Comment by doneill** [comment]
Closing as fixed
