### ISSUE TITLE
How to set BoundingBox to MapView

### ISSUE THREAD

**Issue by DucHM** [Esri/arcgis-runtime-samples-android#157]
Dear,
I want to set BoundingBox for MapView (Android).
How to set it?
Example GoogleMap:
LatLngBounds.Builder builder = new LatLngBounds.Builder();
...............
for (int idx = 0; idx < mLatLongArray.size(); idx++) {
      builder.include(mLatLongArray.get(idx));
}
..............
Bounds bounds = builder.build();
mGoogleMap.moveCamera(CameraUpdateFactory
.newLatLngBounds(bounds, AppConf.dpToPx(72, getResources())));
mGoogleMap.moveCamera(CameraUpdateFactory.zoomOut());

Thanks!

**Comment by shellygill** [comment]
Hi there - you can see examples of setting a map extent to an envelope in various samples - https://github.com/Esri/arcgis-runtime-samples-android/tree/master/Nearby for example. 

For general questions like this about how to develop with the ArcGIS Runtime SDK for Android, the best place to ask is on the geonet forum at https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android. This repo is for the samples in particular, so if you have any problems or suggestions for working with the samples in this repo, that's when you should add an issue here.

Closing as geonet question.
