### ISSUE TITLE
Support  to Integrates ESRI map

### ISSUE THREAD

**Issue by DucHM** [Esri/arcgis-runtime-samples-android#162]
Dear,
I want to Integrates ESRI map in my Android application. But i see the routing function seems data only in the US, Singapore does not have and I only found API service is: 

http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Network/USA/NAServer/Route

I want to ask: Have data in Singapore? What's the Public service API for this routing?

**Comment by doneill** [comment]
@DucHM The service you reference is a sample service and not intended for public facing apps.  For full online routing service please refer to our [ArcGIS online routing service](http://route.arcgis.com/).  We are in the process of updating all our samples to use this service.  Also, please refer to our [GeoNet community](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for more information and further collaboration about the ArcGIS Runtime SDK for Android.  The issues in this repository should be used for specific issues related to our SDK samples.
