### ISSUE TITLE
Unable to find quartz-beta branch

### ISSUE THREAD

**Issue by ddurgaprasad** [Esri/arcgis-runtime-samples-android#202]
ESRI link [](https://developers.arcgis.com/net/quartz/sample-code/sample-code.htm) mentions the Quartz beta samples in this Github repository.

"The code samples described on this page are also available on GitHub(**choose the quartz-beta branch**)."

Where do I find the Quartz branch ?

**Comment by doneill** [comment]
@ddurgaprasad You can select the branch from the upper left corner of the repo: 

![branch](https://cloud.githubusercontent.com/assets/1308001/16881417/f5b9e434-4a6e-11e6-8126-0d879681b5da.png)

Here is a [direct link](https://github.com/Esri/arcgis-runtime-samples-android/tree/quartz-beta) to the branch.  If you fork/clone the repo you can switch branches with the following:  

```
$ git checkout quartz-dev
```

**Comment by ddurgaprasad** [comment]
@doneill  I am able to download.Thanks!
