### ISSUE TITLE
Importing samples into Android Studio

### ISSUE THREAD

**Issue by andygup** [Esri/arcgis-runtime-samples-android#21]
1) Can you elaborate on the comment in the README where it says “NOTE Do not import the project into Android Studio. There is an outstanding issue in Android Studio that requires importing the project in the steps defined below."?

There isn't a link to the outstanding issue, and once you clone it you pretty much have to import the gradle sample project so I'm not clear on what this means.

2) I'm using Android Studio 1.0.1 and immediately after cloning the project I was prompted if I wanted to open the project. I selected "Yes" and then got an Import Project from Gradle window (see screenshot below), then I simply went with the defaults and selected "OK".

This seems a bit different from what the workflow described in the README for importing the gradle sample project. Would it make sense to also include the workflow I have mentioned in a future version of the README?

![image](https://cloud.githubusercontent.com/assets/510440/5712076/9a281176-9a6c-11e4-8a2f-8001e329fac1.png)

**Comment by andygup** [comment]
Interesting... I see I still had to following the **Import Non-Android Studio project** from the Welcome Quick Start step even after going thru the step above. Any clue why using the IDE default prompts didn't install the samples the first time?

**Comment by doneill** [comment]
@andygup Yes, this is why the README recommends not importing the project which is not an ideal workflow.  I do not have an issue # to reference but you can follow the [following thread](https://groups.google.com/forum/#!topic/adt-dev/o8h3Jg9ICGo) to see that the issue is confirmed by Google and add some comments to help get the fix out :-).

**Comment by andygup** [comment]
Thanks, I posted a comment to the thread.

**Comment by kuraii3** [comment]
can you make a youtube video to show how import the sample into android studio please ?

**Comment by doneill** [comment]
@kuraii3 We can consider that after we release beta-2.  For now, after you fork/clone are you having issues [importing the project](https://github.com/Esri/arcgis-runtime-samples-android#import-gradle-sample-project-into-android-studio)?  Depending on the version of Android Studio you are using the verbiage may be slightly different, see screenshot below where you would choose **Import project (Ecilpse ADT, Gradle, etc.)**:  

![import](https://cloud.githubusercontent.com/assets/1308001/14002519/60876b8c-f101-11e5-90d0-ad114cf438d0.png)

Once you have opened the project on import you can open the project with **Open an existing Android Studio project**.  The impeded issue is with respect to opening the project initially with Import.

**Comment by kuraii3** [comment]
@doneill thanks i managed to import it successfully

**Comment by fukemy** [comment]
can not clone by android studio. I can not find arcGis-sample.... to run :(

**Comment by fukemy** [comment]
![screen shot 2018-01-22 at 17 01 58](https://user-images.githubusercontent.com/8202437/35215144-fbbd197c-ff95-11e7-9692-70d90c60a95a.png)
here is my picture sir

**Comment by TADraeseke** [comment]
HI @fukemy. When you click 'Import project' you must select the the /java or /kotlin folder. It looks like you might be selecting the folder above in your screenshot. Can you try that out and let me know how you get on?
