### ISSUE TITLE
Update requirements section in README

### ISSUE THREAD

**Issue by andygup** [Esri/arcgis-runtime-samples-android#22]
It looks like the build.gradle is set to targetSdkVersion 21. The IDE says that SDK 21 requires JDK 7.

![image](https://cloud.githubusercontent.com/assets/510440/5713039/a3b73e8a-9a74-11e4-96d4-7daceef1b950.png)

**Comment by doneill** [comment]
Thanks @andygup for catching that one.  You can change the root projects build.gradle file to set the ```compileSdkVersion``` to a JDK 6 compatible version which all the samples will pick up.

**Comment by doneill** [comment]
Verified
