### ISSUE TITLE
Quartz Beta :- Identify on Geometry

### ISSUE THREAD

**Issue by lanetteamkaushal** [Esri/arcgis-runtime-samples-android#230]
Hello All,

In stable release, we can pass geometry as Identify parameter. But in Quartz Beta I can not find such method. I want to call Identify on Polygon. Is there any method ?

Thanks,
Kaushlendra.

**Comment by willcrick** [comment]
We have identify methods on the GeoView (MapView inherits from GeoView):

For Graphics call one of the identifyGraphicsOverlay methods: https://developers.arcgis.com/android/beta/api-reference/reference/com/esri/arcgisruntime/mapping/view/GeoView.html#identifyGraphicsOverlayAsync(com.esri.arcgisruntime.mapping.view.GraphicsOverlay, android.graphics.Point, double)

For Layers call one of the identifyLayer methods: https://developers.arcgis.com/android/beta/api-reference/reference/com/esri/arcgisruntime/mapping/view/GeoView.html#identifyLayerAsync(com.esri.arcgisruntime.layers.Layer, android.graphics.Point, double)

**Comment by lanetteamkaushal** [comment]
@willcrick Thanks for reply.Basically I want to draw polygon over map and call identify on it.so I have polygon than what should I pass in android.graphics.Point(2nd Argument) ?
Should I pass centre of Polygon?

Thanks,
kaushlendra

**Comment by doneill** [comment]
@lanetteamkaushal We have a [identify-graphic-hittest](https://github.com/Esri/arcgis-runtime-samples-android/tree/quartz-beta/identify-graphics-hittest) which shows how to draw a polygon as a `Graphic`, add it to a `GraphicsOverlay` and add it to a `MapView` and identify.  Yes, create a `android.graphics.Point` as 2nd argument as you suggest.  Take a look at the sample and let me know if you have any further questions.

**Comment by lanetteamkaushal** [comment]
@doneill Thanks. I will try and let you know here.

**Comment by doneill** [comment]
Closing as answered, @lanetteamkaushal please update if you have any additional questions about this.
