### ISSUE TITLE
It can not be valid when i use  layer.setOpacity (0.5f) ?

### ISSUE THREAD

**Issue by itliyalei** [Esri/arcgis-runtime-samples-android#251]
I user ArcGISRuntime.setClientId("############") to develope for app ,when I use layer.setOpacity
(0.5f)  it can not be valid  in android 6.0.1.   But in developer mode it can be valid .

**Comment by doneill** [comment]
@itliyalei Are you referencing a specific example?  Or is this a general pattern question?

**Comment by itliyalei** [comment]
Is it the basic version sdk has some question in the android higher version. Because in the android 5 or android 4, it is running normally.

**Comment by doneill** [comment]
@itliyalei Please share relevant code beyond the reference you made, also include what sample you are working with.

**Comment by ssqgrand** [comment]
android sdk 6.0 version,i invoke layer.setOpacity method not work

**Comment by ssqgrand** [comment]
if i use developer test version,not use  ArcGISRuntime.setClientId("############"),it is normal

**Comment by massive169** [comment]
i have similiar question about that, it seems opacity does not work on certain layer, never try below android 6.0 though.
for example 
i have three layer on mapview,

`ArcGISLocalTiledLayer tiledLayer;`
`ArcGISLocalTiledLayer vkmLayer;`
`KmlLayer kmlLayer;`
and i implement it on slider

`materialSlider.setOnPositionChangeListener(new Slider.OnPositionChangeListener() {
            
            public void onPositionChanged(Slider view, boolean fromUser, float oldPos, float newPos, int oldValue, int newValue) {
                
                    vkmLayer.setOpacity(newPos);
                    tiledLayer.setOpacity(newPos);
                    kmlLayer.setOpacity(newPos);
                    Log.e("vkm opacity","opacity : "+vkmLayer.getOpacity());
                    Log.e("tiled opacity","opacity : "+tiledLayer.getOpacity());
                    Log.e("kml opacity","opacity : "+kmlLayer.getOpacity());
                    mapView.invalidate();
                
            }
        });`


Opacity works on **KmlLayer**, but not for **ArcGISLocalTiledLayer**
any clue?

and this is the log i got

`12-29 16:03:51.683 6158-6158/ E/vkm opacity: opacity : 0.6833278`
`12-29 16:03:51.683 6158-6158/ E/tiled opacity: opacity : 0.6833278`
`12-29 16:03:51.683 6158-6158/ E/kml opacity: opacity : 0.6833278`

**Comment by wangwei5247132** [comment]
hello  friend. Have you solved this problerm? I have the same question
