### ISSUE TITLE
MapOverlay equivalent in quartz 100.0?

### ISSUE THREAD

**Issue by pulink** [Esri/arcgis-runtime-samples-android#271]
In the previous ArcGIS Runtime SDK, MapOverlays were provided. The main benefit of MapOverlays was the ability to paint anything directly over the Map. Is there any equivalent of onPaint(Graphics g) method in the quartz release. 
I am new to JavaFX. if painting over a MapView is possible in JavaFX directly without any GIS support, Kindly let me know.

**Comment by doneill** [comment]
@pulink The `MapOverlay` is available in 10.2 version of the [ArcGIS Runtime SDK for Java](https://developers.arcgis.com/java/).  It is not currently available in v100.0.0 as of yet so there is no equivalent of `onPaint(Graphics g)` in 100.0.  I suggest you take this question to [GeoNet forum for ArcGIS Java](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-java).  Alternatively, you can make a suggestion to [ArcGIS Ideas](https://geonet.esri.com/community/arcgis-ideas/).

**Comment by pulink** [comment]
@doneill Thanks.

**Comment by pulink** [comment]
I have created a Idea on [ArcGis Ideas](https://geonet.esri.com/community/arcgis-ideas/). Anybody, who feels the requirement of MapOverlay, can upvote it [here](https://geonet.esri.com/ideas/12945-introduction-of-mapoverlay-in-arcgis-quartz).
