### ISSUE TITLE
There is something wrong with "feature-layer-definition-expression"

### ISSUE THREAD

**Issue by BenzSamranpong** [Esri/arcgis-runtime-samples-android#275]
I try to import example and run on my LB but I can't! I found this error message. Can someone help me please?

Execution failed for task ':feature-layer-definition-expression:mergeDebugResources'.
> Error: Failed to crunch file F:\ESRITraining\arcgis-runtime-samples-android-master\feature-layer-definition-expression\build\intermediates\exploded-aar\com.esri.arcgisruntime\arcgis-android\100.0.0\res\drawable-mdpi-v4\arcgisruntime_location_display_acquiring_symbol.png into F:\ESRITraining\arcgis-runtime-samples-android-master\feature-layer-definition-expression\build\intermediates\res\merged\debug\drawable-mdpi-v4\arcgisruntime_location_display_acquiring_symbol.png

**Comment by doneill** [comment]
@BenzSamranpong You issue has to do with a Windows file path too long limitation which must be kept below 240 characters.  Try shortening the file path, e.g. `F:\arcgis-runtime-samples-android\...`
