### ISSUE TITLE
How to load shapefile layer with runtime 100

### ISSUE THREAD

**Issue by wuhongsheng** [Esri/arcgis-runtime-samples-android#277]

**Comment by doneill** [comment]
@wuhongsheng We do not as of yet support shapefiles with ArcGIS Android 100.0.0, we do have support with 10.2.x with [ShapefileFeatureTable](https://developers.arcgis.com/android/10-2/api-reference/reference/com/esri/core/geodatabase/ShapefileFeatureTable.html).
