### ISSUE TITLE
no sketchgraphicsoverlay in quartz 100.0.0

### ISSUE THREAD

**Issue by AlisonGou** [Esri/arcgis-runtime-samples-android#279]
hi there,
There is declaration of SketchGraphicsOverlay in the link below
https://github.com/Esri/arcgis-runtime-samples-android/blob/master/map-sketching/src/main/java/com/esri/arcgisruntime/sample/mapsketching/MainActivity.java

however, this class does not belong to arcgis runtime sdk or android api. Therefore, I am guessing it is one of classes in beta? Which class should be used in 100.0.0 as a replacement?

Regards,
Alison

**Comment by shellygill** [comment]
Hi Alison - this class is not part of the API, but is defined within the sample - you can see the source code here - https://github.com/Esri/arcgis-runtime-samples-android/blob/master/map-sketching/src/main/java/com/esri/arcgisruntime/sample/mapsketching/SketchGraphicsOverlay.java

**Comment by AlisonGou** [comment]
hi shellygill,
yes you r right, dumb me. I will close this question  and fade away silently, haha.
have a great day
Alison.

**Comment by shellygill** [comment]
No problem Alison :-)
