### ISSUE TITLE
Update PlaceSearch Sample to use SearchDialog and LocatorSuggestion

### ISSUE THREAD

**Issue by doneill** [Esri/arcgis-runtime-samples-android#28]
Update the **PlaceSearch** sample to use Android ```SearchDialog``` and our new ```LocatorSuggestion``` API.  This will show a more modern place search UI/UX pattern.

**Comment by XuemingRocks** [comment]
Since Android lower than 3.0 is not supported by ArcGIS for Android SDK and search widget works better with Action Bar,  use search widget instead of search dialog for this sample. Also use App Toolkit to add search result to the map.

**Comment by doneill** [comment]
@XuemingRocks Great, that will be a nice improvement.

**Comment by doneill** [comment]
Verified fixed with #36 and updated with #56.
