### ISSUE TITLE
arcgis-vectortiledlayer-url Sample black map window

### ISSUE THREAD

**Issue by TADraeseke** [Esri/arcgis-runtime-samples-android#282]
Possible permissions issue?

Running sample code on Nexus 5.

Map window loads, but only appears as a black background on Nexus 5.
![screenshot_20170220-143658](https://cloud.githubusercontent.com/assets/8885446/23129399/6e7242e6-f77a-11e6-95b1-78130aca6222.png)

When URLs of ArcGISVectorTiledLayer are pulled out of the values -> strings.xml and
loaded separately in a browser ArcGIS.com returns, 'You do not have permissions to access this resource.'

**Comment by doneill** [comment]
@TADraeseke I have reproduced the issue on Nexus 5 and provided a fix.  Please pull the latest from master and verify it works for you.

**Comment by TADraeseke** [comment]
Works, thanks!
