### ISSUE TITLE
Dynamic SubLayer Reorder sample

### ISSUE THREAD

**Issue by salihyalcin** [Esri/arcgis-runtime-samples-android#29]
Is there dynamicsublayer reorder sample for android is available ? 

iOS has this issue but android dont have

Thanks in advance.

**Comment by doneill** [comment]
@salihyalcin We do not currently have a this sample in Android. Please share your interest in this sample from iOS so we can think about providing this in Android.  Are you interested in a straight port from iOS, or do you have a more specific use case to consider?

**Comment by salihyalcin** [comment]
We are developing an app that using arcgis android sdk and ios sdk for our municipality. This property very useful for our app. At the ios side we can use properly. When pass the android side it is not easy to do. We consider if ios side has this property android side may has this property too. 

Dynamic sublayer reorder samples properties are add layer , drag layer for reorder and delete layer like arcgis desktop done. 

Thats way we consider to use this property. 

Thanks for interest

**Comment by doneill** [comment]
@salihyalcin I have added this for Android.  What is your timeline as it is planned for next release?  I can get something to you sooner, but realistically it won't be until after our developer summit in March.

**Comment by salihyalcin** [comment]
@doneill No matter its time.. It will do my bussines at your mentioned date. I'm so excited to try this :) 
My project timeline is up to date :)

**Comment by salihyalcin** [comment]
@doneill Is this sample is still being considered ? I'm looking forward to this example :)

**Comment by doneill** [comment]
@salihyalcin Yes, this sample is being considered and currently added to our list of sample to be developed.

**Comment by salihyalcin** [comment]
Hello Dan, 
I've made this example by myself. If you want to add this example to your examples you can look my repo via link below :+1: 

https://github.com/salihyalcin/DynamicSubLayerReorderSample
