### ISSUE TITLE
draw a line from a point by giving angle angle and distance to next point

### ISSUE THREAD

**Issue by PranavMS007** [Esri/arcgis-runtime-samples-android#296]
Actually this is not an issue. This is my clients requirement,

I want to know how can i draw another line which respect of one point means we have first  ploted one poit on map. Then i know the next point's  distance to this point and angle. 

My question is how can i draw that line  And this process may continued till get my polygon .

If my shape of polygon is triangle.

Initial i know the first point. Then i plot that point in map. At the same same it should pop up the box to ask the angle and distance to next point. 
Then i fill the boxes and submit it . It should draw the line form first point to next one based on given distance and angle. 
Then it again pop up the same box to asking the angle and distance of next point 

Now we know the third point is same as the first point. so it should draw this as a polygon  .

I think you people got my idea . Please suggest me some libraries or some way to achieve this process.

Thanks advance.
Pranav MS

**Comment by PranavMS007** [comment]
Hello is there any one here?

**Comment by nohe427** [comment]
I believe this was answered here:

https://community.esri.com/message/677451-draw-a-line-from-a-point-by-giving-an-angle-and-distance-to-next-point
