### ISSUE TITLE
 GeoEvent, local geofencing and tracking simulator

### ISSUE THREAD

**Issue by urbutisj** [Esri/arcgis-runtime-samples-android#342]
Hi, please make some sample with GeoEvent, local geofencing and  tracking simulator. For example if point comes to polygon, user gets notification about it, if he left the polygon, he gets notification again. 
It would be very helpful.

**Comment by doneill** [comment]
Thanks @urbutisj We have a Local Geofence demo in this [repo](https://github.com/Esri/arcgis-runtime-demos-android/tree/master/2016-DS/LocalGeofence).

**Comment by urbutisj** [comment]
Thanks for reply @doneill . How about other samples ? GeoEvent and track simulator. I explained these here: https://geonet.esri.com/thread/195974-maybe-someone-knows-how-to-solve-these-three-tasks
I really need the samples for that...

**Comment by doneill** [comment]
@urbutisj I commented in the GeoNet post.  We can continue the conversation over there.  Please feel free to submit a samples request issue here if you like, be specific about your expectations if you choose to do so.

**Comment by urbutisj** [comment]
@doneill I replied on Geonet, but didn't get any answer. Could you make the Geofencing sample for Quartz version ? Thanks!

**Comment by doneill** [comment]
@urbutisj Yes, I can't provide a timeline but we will be updating geofencing demo to v100.x.x.

**Comment by urbutisj** [comment]
Thanks ! :)
