### ISSUE TITLE
StandardOfflineLicencing returning error 400 invalid redirect_uri

### ISSUE THREAD

**Issue by ashimkansal** [Esri/arcgis-runtime-samples-android#345]
Hello Team,

I am following the below link  to remove "Licenced for debveloper use only" from my mapview using standard licencing:

https://github.com/FernandaOchoa/Arcgis-Samples-Android-SDK/blob/master/StandardLicenseOffline/src/main/java/com/esri/arcgis/android/samples/standardlicenseoffline/MainActivity.java

Outhview showing the error 400 invalid Redirect_Uri.

Please suggest?

**Comment by doneill** [comment]
@ashimkansal The steps to get this sample working have been updated to the following taking note of the the additional 2 steps # 4 & 5: 

- Browse to the [ArcGIS developers site](https://developers.arcgis.com).
- Sign in with your ArcGIS developer account.
- Create an application. 
- Go to the **Authentication** tab for your new application.
- Add `urn:ietf:wg:oauth:2.0:oob` to the redirect URIs.
- Initialize the `client_id` string resource, **res/values/strings.xml**, with the client id string and run the sample. 

The documentation has been updated in the 10.2.9 version of the repo. You can get the latest version of the 10.2.x samples by checking out the `v10.2.9` tag replacing `[branchname]` with the name you want to use: `$ git checkout -b [branchname] v10.2.9`

**Comment by ashimkansal** [comment]
Thanks Doneill,

After adding urn:ietf:wg:oauth:2.0:oob to redirect URIs, i am getting the blank screen inside outhview.

**Comment by ashimkansal** [comment]
Doneill, now it works. But every time i come online, i need to login into arcgis. But right now as a developer i know the credentials of arcgis account but if i release the app then how users login into arcgis?

**Comment by doneill** [comment]
@ashimkansal Anyone with a valid ArcGIS Online account should be able to log into the app.
