### ISSUE TITLE
How to load 3D scenes？

### ISSUE THREAD

**Issue by wuhongsheng** [Esri/arcgis-runtime-samples-android#351]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by doneill** [comment]
@wuhongsheng We have 2 samples showing how to load 3D scenes: 

- [display-scene](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/display-scene)
- [scene-layer](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/scene-layer)

**Comment by zj8487** [comment]
Hi @doneill, sorry to trouble you.
I noticed that we can access data attributes from layers (SceneLayer with multipatch geometries) and graphics with javascript api 4.6. but failed with arcgis-runtime-android 100.2.  

is it possible to add a sample for this?
