### ISSUE TITLE
Where is the data in offline samples 

### ISSUE THREAD

**Issue by gisxy** [Esri/arcgis-runtime-samples-android#363]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by doneill** [comment]
@gisxy All offline samples have data links in the README of the sample under **Provision your device**.  See [Feature Layer Geodatabase](https://github.com/Esri/arcgis-runtime-samples-android/blob/master/feature-layer-geodatabase/README.md#provision-your-device) as an example.

**Comment by gisxy** [comment]
thank you!
