### ISSUE TITLE
How do you scale to the filtered layer?

### ISSUE THREAD

**Issue by AlyssaChia** [Esri/arcgis-runtime-samples-android#364]
Now my first layer is colorful, and it covers the other layer according to the filter condition. Now I want to scale the map to two layers

**Comment by TADraeseke** [comment]
Hi Alyssa,

Just to be clear, by scale you mean pan and zoom the map to show your layers' full extent?

You can start by using [getFullExtent() ](https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/layers/Layer.html#getFullExtent())on your layer. 

This will return an [Envelope](https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/geometry/Envelope.html) defining a rectangular view area around your layer.

Next, set the Envelope to a [Viewpoint](https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/mapping/Viewpoint.html#Viewpoint(com.esri.arcgisruntime.geometry.Envelope)).

Finally, set the [MapView](https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/mapping/view/MapView.html#setViewpointAsync(com.esri.arcgisruntime.mapping.Viewpoint, float, com.esri.arcgisruntime.mapping.view.AnimationCurve)) to the Viewpoint.

Let me know how you get on!

**Comment by AlyssaChia** [comment]
Thank you for your help. I want to move to my dynamic layer after filtering the range.I have more data.I can't want to use the query method.

**Comment by TADraeseke** [comment]
Hi Alyssa,

Could you post your question on our [Geonet forums](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) please? Questions like this are better served there so other users can learn from your questions.

When you post, please add as much detail as you can. It'll help me better understand your work :)

**Comment by AlyssaChia** [comment]
Thank you,I went there to ask the question in detail:)

**Comment by TADraeseke** [comment]
Sorry Alyssa, I don't see it in Geonet. Could you past a link please? thanks!

**Comment by AlyssaChia** [comment]
Thanks for caring This is the tip that he gave me.  I am waiting for the audit.
  A moderator will review your request to join the GeoNet community shortly. In the meantime feel free to explore the community (Note: By clicking this link all Esri Account sessions will be logged out). You will be able to contribute once your account has been approved. If you need assistance with your request, please Contact Us.
