### ISSUE TITLE
Does not found Android ArcGIS offline edit and sync feature but I have found for iOS (https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Edit%20data/Offline%20edit%20and%20sync) . I am using ArcGIS 100.1.0. How to solve this issue?

### ISSUE THREAD

**Issue by satyaki1988** [Esri/arcgis-runtime-samples-android#365]
**Does not found Android ArcGIS offline edit and sync feature but I have found for iOS (https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Edit%20data/Offline%20edit%20and%20sync) . I am using ArcGIS 100.1.0. How to solve this issue?**

**Comment by doneill** [comment]
@satyaki1988 Android does not have this sample as of yet.  We are looking to implement.
