### ISSUE TITLE
How to show red points by longitude&latitude

### ISSUE THREAD

**Issue by Midicy** [Esri/arcgis-runtime-samples-android#371]
Such as the title,
  i want to show red pints by longitude&latitude in Android,like this
![image](https://user-images.githubusercontent.com/21966933/29345906-718ebd12-8274-11e7-903a-648a792a29ae.png)
  what can i do?

**Comment by TADraeseke** [comment]
HI Midicy,

Try following this sample here which shows a `Point` being drawn on the map with a `SimpleRenderer`

https://github.com/Esri/arcgis-runtime-samples-android/blob/4ed19e71d73d634b97dd305d03e1a2c27ebb7fa9/add-graphics-renderer/README.md

We prefer discussions like this to be on our [Geonet forums](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android), so others can learn from and contribute to your issue. Cheers!
