### ISSUE TITLE
Updating version 100.1.0 cause app name change to Android API

### ISSUE THREAD

**Issue by salihyalcin** [Esri/arcgis-runtime-samples-android#372]
Hi Guys, 

I've just realized that after updating v100.1.0, app name change to Android API. I think that It could be related with my project and I opened a new project and try to add Esri Android SDK 100.1.0. So app name changed to Android API too at new project. 

It is bug or I am missing something 

Here I added a screenshot from my tryings. 

<img src="https://user-images.githubusercontent.com/9201717/29352320-f8cf446e-826e-11e7-87fc-09f8944f9a52.png" width="220">

**Comment by salihyalcin** [comment]
When I change `app_name` id to `app_name_label` in my` strings.xml` app name return to correct type. But in default SDK change the app name.

**Comment by wuhongsheng** [comment]
you can try add  tools:replace="android:label" in Manifest file
<img width="684" alt="2017-09-05 2 10 54" src="https://user-images.githubusercontent.com/10295461/30047487-1bf3f306-9244-11e7-9788-a4d70a15f02b.png">

**Comment by doneill** [comment]
@salihyalcin Need more information to assist.  Can you provide the full steps to reproduce this?  Are you saying that you had an existing app based on 100.0.0 and all you did was update the dependency to 100.1.0?  I have yet to reproduce that.

**Comment by nohe427** [comment]
@doneill - This is reproducible when using a different language localization and using the default string resource `app_name`.

**Comment by shellygill** [comment]
Hi @salihyalcin - we've addressed this issue in the 100.2 release of the ArcGIS Runtime SDK for Android - more info on the release is at https://blogs.esri.com/esri/arcgis/2017/12/18/whats-new-in-arcgis-runtime-sdk-100-2-0/. Please let us know if you have any continuing problems once you've upgraded to version 100.2 - you could reopen this issue, or let us know on the [GeoNet community](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D).
