### ISSUE TITLE
how to load .gpkg file

### ISSUE THREAD

**Issue by wuhongsheng** [Esri/arcgis-runtime-samples-android#380]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Feature or Bug?
1.how to load .gpkg file

**Comment by doneill** [comment]
@wuhongsheng We do not yet support geopackages with v100.x.x, with 10.2.9 you use the [Geopackage](https://developers.arcgis.com/android/10-2/api-reference/reference/com/esri/core/geodatabase/Geopackage.html) class to open *.gpkg files.
