### ISSUE TITLE
How to use icon font within TextSymbol ?

### ISSUE THREAD

**Issue by ddcrobert** [Esri/arcgis-runtime-samples-android#381]
Icon fonts are getting more and more common within projects.
I would like to integrate [Map Icons](http://map-icons.com/) within TextSymbol.
This would provide a way to build icons easily via CompositeSymbol.

Tried lines like
`TextSymbol textSymbol = new TextSymbol(32, "\ue85d", Color.BLUE, TextSymbol.HorizontalAlignment.CENTER, TextSymbol.VerticalAlignment.MIDDLE);
        textSymbol.setFontFamily("map-icons");`

The struggle is that Android relies on Typeface to integrate theses fonts, and I didn't find a way to set TextSymbol's Typeface...

Can you provide a sample with the workaround ?

By the way, I managed to do that with iOS.

**Comment by doneill** [comment]
@ddcrobert Direct support for icons as symbols is coming in a future release.  You mention that you are able to do this with iOS, are you using the same developer pattern that you reference?

**Comment by ddcrobert** [comment]
Yes, the very same way, besides language differences.
`let textSymbol = AGSTextSymbol(text: "\u{e85d}", color: UIColor.nokiaDark, size: 32, horizontalAlignment: .center, verticalAlignment: .middle)
        textSymbol.fontFamily = "map-icons"`

**Comment by doneill** [comment]
@ddcrobert Ok, I will take a look, thanks!

**Comment by doneill** [comment]
On Android you are trying to use the font as an asset in the APK?  Currently we do not support a setting the `Typeface`, a workaround is to programmatically create a `TextView` and set the location based on tapped screen location: 

```kotlin
// respond to single taps on mapview
mapView.onTouchListener = object:DefaultMapViewOnTouchListener(this, mapView) {
    override fun onSingleTapConfirmed(motionEvent: MotionEvent?): Boolean {
        // get the point that was clicked and convert it to a point in map coordinates
        val screenPoint: android.graphics.Point = android.graphics.Point(motionEvent!!.x.toInt(), motionEvent.y.toInt())
        // create a TextView
        val mapIconView = TextView(applicationContext)
        // create Typeface from assets folder, /assets/fonts/
        val mapIconTypeFace = Typeface.createFromAsset(assets, "fonts/map-icons.ttf")
        // set the Typeface to the TextView
        mapIconView.typeface = mapIconTypeFace
        // create a layout param
        mapIconView.layoutParams = ViewGroup.LayoutParams(100, 100)
        // place the TextView using screen x/y location
        mapIconView.x = (screenPoint.x).toFloat() 
        mapIconView.y = (screenPoint.y).toFloat()
        // set the text, size, color of font
        mapIconView.text = "\ue85d"
        mapIconView.textSize = 32f
        mapIconView.setTextColor(Color.WHITE)
        // add TextView to MapView
        mapView.addView(mapIconView)

        return super.onSingleTapConfirmed(motionEvent)
    }

}
```

Let me know if this addresses your issue.  This would also be good information for [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) forums, I encourage you to join and share your questions with the community.

**Comment by ddcrobert** [comment]
Actually, this workaround is limited to static map.
Map / screen conversion is often a good solution, e.g center a graphic on top half. I could rely on it to place TextView accordingly to my Graphics (they're built from data) and give them an transparent symbol.
I also think I would be able to "clip" theses TextViews based on MapView bounds.

My main concern is about zoom, pan and rotation events.
I'm pretty sure I would encounter latency and/or performance issues.

I also thought of using dynamically generated Image (some sort of TextView to Image conversion) and use them as symbol, but that's a bad idea, since there won't be quality improvment.

So, I prefer stick w/ images on Android, after all, that's the classic way most people are using.

**Comment by doneill** [comment]
@ddcrobert Yes, agreed static map as the `mapIconView.text` is not bound by the geometry.  You can address this by creating a graphic at original tapped location, get it's geometry, and convert to screen points while listening to MapView scale changes `MapView.addMapScaleChangedListener`.  This will keep the font over the location on zoom/pan/rotate events, but agreed there is some overhead with this workaround.
