### ISSUE TITLE
PlaceSearch sample crashes when Search Button is clicked

### ISSUE THREAD

**Issue by z3ke1r** [Esri/arcgis-runtime-samples-android#4]
When inputting an address/place and pressing "Enter" the location is found, however if instead of pressing "Enter" I click the Search Button again the application crashes with an error. I am testing on the AVD
![placesearch crash](https://cloud.githubusercontent.com/assets/8351123/4290092/e06aca40-3db8-11e4-9f56-afe3e3acdb33.PNG)
.

**Comment by doneill** [comment]
Verified fixed with #56
