### ISSUE TITLE
Dont support on the fly display for different spatial reference system layer

### ISSUE THREAD

**Issue by salihyalcin** [Esri/arcgis-runtime-samples-android#42]
I have basemap and its spatial reference is written below. I'm adding this basemap TiledMapServiceLayer

(BaseMap) - 
Spatial Reference: PROJCS["ITRF_96_UTM_Zone_35N",GEOGCS["GCS_GRS_1980",DATUM["D_ITRF_1996",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",30.0],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]

And I have DynamicLayer. I am adding this ArcGISDynamicMapServiceLayer and Spatial reference is;

(DynamicLayer)
Spatial Reference:
 GEOGCS["Geographic Coordinate System",DATUM["D_WGS84",SPHEROID["WGS84",6378137.0,298.257223560493]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]] 

Only the layers having the same spatial reference of basemap are visible on the map. When basemap layer and dynamic layer have different spatial reference, dynamic layers not visible on the map. At the iOS SDK side there is not like this problem. Or anything else i'm forgetting to add?  Or it is bug ?

**Comment by willcrick** [comment]
is this a problem in a particular sample? If it is, please mention the sample you are having problems with, if not and this a general SDK/API question please raise this on the geonet forum here:
https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android

**Comment by doneill** [comment]
@salihyalcin Sounds like this is not a sample specific issues, as @willcrick mentioned, you should post this in to forum and share some specific code from your app as well.

**Comment by doneill** [comment]
Closing and marked as GeoNet question
