### ISSUE TITLE
How to load shape file from SDCard?

### ISSUE THREAD

**Issue by klower** [Esri/arcgis-runtime-samples-android#425]
How to load shape file from SDCard? l cannot find any api

**Comment by eric906** [comment]
This capability is coming in our next major release, just 2 weeks away. 100.2. Stay tuned!

**Comment by TADraeseke** [comment]
Hi @klower 

This has been added to our 100.2 [release of the ArcGIS Runtime SDK for Android](https://blogs.esri.com/esri/arcgis/2017/12/18/whats-new-in-arcgis-runtime-sdk-100-2-0/).
 
Here's our first sample using shapefiles: https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/symbolize-shapefile

Let us know if you have any more questions either here or on the [GeoNet community](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D).
