### ISSUE TITLE
l got an error: Cannot call this method in this context

### ISSUE THREAD

**Issue by klower** [Esri/arcgis-runtime-samples-android#432]
I got an error: 
  Caused by: com.esri.arcgisruntime.ArcGISRuntimeException: Cannot call this method in this context
                                                                                                      at com.esri.arcgisruntime.internal.jni.CoreFeatureTable.nativeCreateFeatureWithAttributes(Native Method)
                                                                                                      at com.esri.arcgisruntime.internal.jni.CoreFeatureTable.a(SourceFile:415)
                                                                                                      at com.esri.arcgisruntime.data.FeatureTable.createFeature(SourceFile:539)

when l called shapefileFeatureTable.createFeature(attributes, polygon);

my codes are like this:
    ShapefileFeatureTable shapefileFeatureTable = new ShapefileFeatureTable(
                Environment.getExternalStorageDirectory() + getString(R.string.local_folder) + getString(R.string.file_name));
        Log.d(getClass().getSimpleName(), "shapefileFeatureTable: " + shapefileFeatureTable.canAdd());

        PointCollection points = new PointCollection(SpatialReference.create(4326));

        //add points to the point collection
        points.add(new Point(-2.643077012566659,56.077125346044475));
        points.add(new Point(-2.6428195210159444,56.07717324600376));
        points.add(new Point(-2.6425405718360033,56.07774804087097));
        points.add(new Point(-2.6427122328698127,56.077927662508635));
        points.add(new Point(-2.642454741319098,56.07829887790651));
        points.add(new Point(-2.641853927700763,56.078526395253725));
        points.add(new Point(-2.6409741649024867,56.078801809192434));
        points.add(new Point(-2.6399871139580795,56.07881378366685));
        points.add(new Point(-2.6394077579689705,56.07908919555142));
        points.add(new Point(-2.638764029092183,56.07917301616904));
        points.add(new Point(-2.638485079912242,56.07896945149566));
        points.add(new Point(-2.638570910429147,56.078203080726844));
        points.add(new Point(-2.63878548672141,56.077568418396));
        points.add(new Point(-2.6391931816767085,56.077197195961084));
        points.add(new Point(-2.6399441986996273,56.07675411934114));
        points.add(new Point(-2.6406523004640934,56.076730169108444));

        //create a polygon from the point collection
        Polygon polygon =  new Polygon(points);
        Feature feature = shapefileFeatureTable.createFeature(attributes, polygon);
        final ListenableFuture<Void> result = shapefileFeatureTable.addFeatureAsync(feature);

**Comment by klower** [comment]
what i want to do is to convert my GEOJson data to Shape file and save it in SDCard. but l cannot find any api in 100.2.0 version

**Comment by eric906** [comment]
@klower - There isn’t an API to directly convert GeoJSON to Shapefile in Runtime 100.2. You could potentially use third-party or open source GeoJSON/shapefile APIs, there are many out there, to do the conversion yourself. Then, you could read and edit that resulting shapefile with ArcGIS Runtime APIs.

**Comment by klower** [comment]
Would you please give an advice or a link that l can find api to convert GeoJSON to Shapefile, l cannot find any third-party l can use on Android platform.

**Comment by pengfei666** [comment]
https://blog.csdn.net/xuzhuang1996/article/details/54380269
