### ISSUE TITLE
do wmslayer support wms 1.1.1？

### ISSUE THREAD

**Issue by hsiaray** [Esri/arcgis-runtime-samples-android#433]
i tried to use a wms 1.1.1 url from a geoserver, but it doesn't work.. 

"cause:com.esri.arcgisruntime.ArcGISRuntimeException: Invalid XML.
mAdditionalMessage:XML comment is not well-formed."

if this is not supported now, will it be supported in next versions such as 100.3? thanks : )

**Comment by shellygill** [comment]
Hi @hsiaray - yes we do plan to improve on our WMS support - from our release notes at https://developers.arcgis.com/android/latest/guide/release-notes.htm:
> "Only WMS version 1.3 is supported at this release, but support for other versions will be added in a future release."

I'm afraid we can't promise this in a specific release or at a specific date at this point, but it is in our plans. The best place to check this info in new releases is in the Esri Blog posts (https://blogs.esri.com/esri/arcgis/tag/arcgis-runtime-sdk-for-android/), or in the Release Notes. 

As per our new issue template, we think general questions like are best asked on our [Geonet forums](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android), so others can learn from and contribute to your issue. If you have specific questions about, or problems with, the sample code that is contained in this repo, then add issues in this repo.

**Comment by hsiaray** [comment]
Got it, thank you @shellygill 👍
