### ISSUE TITLE
Whether 100.x has a measuring tool

### ISSUE THREAD

**Issue by 2Exception** [Esri/arcgis-runtime-samples-android#446]
I need to calculate the distance and the area！

**Comment by TADraeseke** [comment]
Hi @2Exception. Checkout the GeometryEngine:

http://android:8080/docs/api/doc/api-doc/arcgis-android/reference/com/esri/arcgisruntime/geometry/GeometryEngine.html

**Comment by abuhmead1987** [comment]
invalid link

**Comment by TADraeseke** [comment]
Link updated, thanks @abuhmead1987
