### ISSUE TITLE
100.2 Identification problem

### ISSUE THREAD

**Issue by goldze** [Esri/arcgis-runtime-samples-android#452]
How to identify the element information at the point position in the map?

ListenableFuture<List<IdentifyLayerResult>> identifyLayerResultsFuture = mMapView
                .identifyLayersAsync(screenPoint, 20, false, 10);
List<IdentifyLayerResult> identifyLayerResults = identifyLayerResultsFuture.get();
        for (IdentifyLayerResult identifyLayerResult : identifyLayerResults){
              List<GeoElement> elements = identifyLayerResult.getElements();
         }
The elements obtained by this method is empty？

Thank for help！

**Comment by TADraeseke** [comment]
Hi @goldze - Thanks for your question.

I think your issue is that `.identifyLayersAsync(...)` is asynchronous and therefore needs a listener to check when the identify is done. For example:

```    
    ListenableFuture<List<IdentifyLayerResult>> identifyLayerResultsFuture = mMapView
        .identifyLayersAsync(screenPoint, 20, false, 10);
    identifyLayerResultsFuture.addDoneListener(() -> {
      try {
        List<IdentifyLayerResult> identifyLayerResults = identifyLayerResultsFuture.get();
        for (IdentifyLayerResult identifyLayerResult : identifyLayerResults) {
          List elements = identifyLayerResult.getElements();
        }
      } catch (InterruptedException | ExecutionException e) {
        e.printStackTrace();
      }
    });

**Comment by goldze** [comment]
@TADraeseke 
  Thank you, but my problem is still unsolved.
List elements = identifyLayerResult.getElements();
Elements size is still 0.
![1](https://user-images.githubusercontent.com/17448148/36582067-da32d534-18aa-11e8-9fc9-4fdd7faed2a7.png)

**Comment by puneetkumar1011** [comment]
Hi @goldze 
I am able to get Layer Results if I have a Screenpoint by using below code.
private void geoElementsCountFromResult(IdentifyLayerResult result) {
        List<IdentifyLayerResult> tempResults = new ArrayList<>();
        tempResults.add(result);
        int index = 0;
        IdentifyLayerResult identifyResult = tempResults.get(index);
        if (identifyResult.getSublayerResults().size() > 0) {
            String siteName = Objects.requireNonNull(identifyResult.getSublayerResults().get(index).getElements().get(index).getAttributes().get("SiteName")).toString();
            String siteCode = Objects.requireNonNull(identifyResult.getSublayerResults().get(index).getElements().get(index).getAttributes().get("SiteCode")).toString();
            getMarkerPopUp(siteName, siteCode);
        }
    }

But how to get data from all layers and sublayers using IdentifyLayerResult.Can you please suggest me asap?
Thank you

**Comment by puneetkumar1011** [comment]
Hi @TADraeseke 

I am able to get Layer Results if I have a Screenpoint by using below code.

private void geoElementsCountFromResult(IdentifyLayerResult result) {
List tempResults = new ArrayList<>();
tempResults.add(result);
int index = 0;
IdentifyLayerResult identifyResult = tempResults.get(index);
if (identifyResult.getSublayerResults().size() > 0) {
String siteName = Objects.requireNonNull(identifyResult.getSublayerResults().get(index).getElements().get(index).getAttributes().get("SiteName")).toString();
String siteCode = Objects.requireNonNull(identifyResult.getSublayerResults().get(index).getElements().get(index).getAttributes().get("SiteCode")).toString();
getMarkerPopUp(siteName, siteCode);
}
}

But how to get data from all layers and sublayers of Map.Can you please suggest me?
From this URL i am trying to fetch all details from the Map layers:-
[](https://mapservices.sbasite.com/arcgis/rest/services/Google/MobileiOS3/MapServer)

Thank you
