### ISSUE TITLE
Find Address No result

### ISSUE THREAD

**Issue by goldze** [Esri/arcgis-runtime-samples-android#455]
final ListenableFuture<List<SuggestResult>> suggestionsFuture = mLocatorTask.suggestAsync(address);
        suggestionsFuture.addDoneListener(new Runnable() {
            @Override
            public void run() {
                List<SuggestResult> suggestResults = suggestionsFuture.get();
            }
        });

suggestResults  size is 0

discovery "mLocatorTask.getLocatorInfo().isSupportsSuggestions()" is return false;
How can I solve it?  Thanks!

**Comment by TADraeseke** [comment]
Hi Goldze, could you share your code through github so I can try to reproduce this? Thanks!
