### ISSUE TITLE
Feature Query

### ISSUE THREAD

**Issue by 2Exception** [Esri/arcgis-runtime-samples-android#458]
hi!
Excuse me, 
v100.x How to query Global Feature?
old 10.x It can be passed through FindTask, So what about 100.x?
Thank you very much for your answer!

**Comment by TADraeseke** [comment]
I believe this sample shows what you're looking for:

https://github.com/Esri/arcgis-runtime-samples-android/blob/8be499ad27f36a58a83d7266826837e6fbaa1b6a/java/feature-layer-query/src/main/java/com/esri/arcgisruntime/samples/featurelayerquery/MainActivity.java
