### ISSUE TITLE
当加载shp文件后浏览到部分图形时App出现闪退

### ISSUE THREAD

**Issue by chunxueer** [Esri/arcgis-runtime-samples-android#476]
# 当加载shp文件后浏览到部分图形时App出现闪退
您好：
1、 当我加载shp文件后浏览到部分图形时App出现闪退。
2、shp 中图形可能存在拓扑错误，以及字符集问题；
3、 能否告知时间操作的正确方式，非常感谢！
运行环境为: `com.esri.arcgisruntime:arcgis-android:100.2.1`、`android 7.1`

错误信息：
05-23 11:21:59.098 18557-18714/com.app.test A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 18714 (com.app.test)
    [ 05-23 11:21:59.100   388:  388 W/         ]
    debuggerd: handling request: pid=18557 uid=10132 gid=10132 tid=18714

**Comment by pengfei666** [comment]
可否分享下数据？

**Comment by changanxian** [comment]
你的问题无法复制， 请以后使用 https://community.esri.com/ 网站和英文， 及数据报告问题， 谢谢！
