### ISSUE TITLE
ExportTileCacheTask E/ArcGIS﹕ No data tile ETag couldn't be retrieved

### ISSUE THREAD

**Issue by fengleige131** [Esri/arcgis-runtime-samples-android#49]
when I user my own MapService in ExportTileCacheTask  Sample，it has the error:  No data tile ETag couldn't be retrieved

**Comment by fengleige131** [comment]
I have find the problem,it is that this sample need the ArcGIS Server 10.2.2 to publish the mapServer.it is meen from ArcGIS Server 10.2.2 ,we can  download the tilecache of the mapserver.

**Comment by xfgood** [comment]
hi，
Is that settled?
