### ISSUE TITLE
ServiceFeatureTable.QueryFeatureFields.LOAD_ALL not working properly

### ISSUE THREAD

**Issue by minakshibh** [Esri/arcgis-runtime-samples-android#503]
I have been trying to load all the attributes in the features selected using ServiceFeatureTable, but doesn't seems to work properly. Most of the time it return attributes values as null. Below is the code,

            Geometry geometry = GeometryEngine.simplify(selectionGraphic.getGeometry());
            QueryParameters query = new QueryParameters();
            query.setGeometry(geometry);
            query.setOutSpatialReference(SpatialReferences.getWgs84());

            ListenableFuture<FeatureQueryResult> selectFuture = serviceFeatureTable.queryFeaturesAsync(query, ServiceFeatureTable.QueryFeatureFields.LOAD_ALL);

            selectFuture.addDoneListener(() -> {
                try {
                    FeatureQueryResult features = selectFuture.get();
                    selectableLayer.selectFeatures(features);

                    selectFeatures(features);
                }
                catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }
            });

Can anyone please help me to provide any solution for this?

**Comment by TADraeseke** [comment]
Hello minakshibh,

First off, can you confirm that you're successfully selecting features?

Second, could you share the code where you're attempting to access the attribute information?

This sample may help: https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/feature-layer-query

**Comment by minakshibh** [comment]
Hello TADraeseke,

Yes, I'm able to select features properly.

It is a simple call to getAttributes() method after selecting features which returns null value.

    feature.getAttributes()

But if I load the features one by one, it returns proper values on attributes but I think we implement LOAD_ALL to overcome this problem.

**Comment by TADraeseke** [comment]
Ahh, no. You do have to load the features one by one, as you're doing.

The QueryFeatureFields.LOAD_ALL requests all available _attribute fields_ to be returned from the service, not to automatically load all features within your app.

**Comment by minakshibh** [comment]
Yes, I only need the _available attribute fields_. QueryFeatureFields.LOAD_ALL returns all attributes as null. I tried to load all features one by one just to get the attributes nothing else, which was supposed to return using LOAD_ALL method. 

Please let me know if I'm not clear enough with my issue.

**Comment by minakshibh** [comment]
Hi @TADraeseke 

I have created a sample project to demonstrate the issue in detail. I have also attached screenshots and a sample video link in the README.md which shows the issue occurred in the sample. Please have a look and let me know if you need any further assistance regarding it.

https://github.com/minakshibh/arcgis-feature-layer-selection-sample

Thanks

**Comment by TADraeseke** [comment]
Hi @minakshibh,

Are you still seeing the issue today? The service is used in other samples and can be edited (both attributes and geometry) in these other samples. Its possible another user was editing them at the same time?

When I try to reproduce this now, most fields are not null (some are null because they are actually null on the service).

Thanks,
Trevor

**Comment by minakshibh** [comment]
Hi @TADraeseke,

I have tested this again and I'm still facing this issue sometime. I have also tried using one of my own service and the issue is there also. So I'm not sure if that is a service edition related issue.

Thanks,
Minakshi

**Comment by minakshibh** [comment]
Have anyone got a solutions for this issue? I'm still facing this, even after updating the sdk to latest version.

**Comment by TADraeseke** [comment]
Hello! I asked a colleague to take a look at this. His response...

Every time a selection is made the layer is removed and added. The query for adding the layer (this queries only min number of attributes) is overriding the query that is called in the code as both of them are asynchronous calls (doesn’t guarantee the order). This may be why we're seeing full attributes sometimes but null most of the times.

This modified code demonstrates appropriate use of the layer and table and always loads all attributes.
https://gist.github.com/rchintapalli/42e8f837aec34e92ee33b501f7a64b02

Hope this clarifies things!
