### ISSUE TITLE
MapView Scale changes automatically when switching between screens

### ISSUE THREAD

**Issue by minakshibh** [Esri/arcgis-runtime-samples-android#504]
I have set the map scale to some value after loading the layers. But when I open some activity and return back to map screen, most of the time it automatically scale the map to its default value and the whole map is visible. I have tried using mapView.pause() and mapView.resume() method but didn't work. Can anyone help me out what could be the possible solution for this issue?

**Comment by TADraeseke** [comment]
This is to do with the Android life cycle destroying and recreating views. You can read more about how it relates to the ArcGIS runtime here: http://developersdev.arcgis.com/android/latest/guide/handle-device-configuration-changes.htm

**Comment by TADraeseke** [comment]
To your particular comment. Are you setting your viewpoint in onCreate()? I suspect what you're seeing is that some of the time your app is staying within the onResume()/onPause() parts of the life cycle and you're seeing the map's viewpoint change whenever the Android OS chooses to call onCreate().

**Comment by minakshibh** [comment]
I do implement the viewpoint code in the onCreate(), but I'm not implementing any code in the onResume() and onPause() methods apart from mapView.pause() and mapView.resume(). So I'm not sure if this is a problem with the life cycle of activities. I also tried opening an empty activity on button click and presses back button. It still shows the showing the same issue. I also tried by checking the Mapscale value in onResume() and it gives the exact value which was set previously but as soon the map shows properly it automatically change its scale to default value.

**Comment by TADraeseke** [comment]
Can you share your code (or at least your life cycle code)? I think I'll need to repro this to be able to help. Thanks!

**Comment by minakshibh** [comment]
Hi TADraeseke,

I have created a sample application which demonstrate this issue.

https://github.com/minakshibh/SampleMap

Do let me know if there is anything you need from my side.

**Comment by TADraeseke** [comment]
Thanks ok! I was able to reproduce this now.

What I'd recommend is instead of the drawStatusChanged listener, etc, instead in your onCreate use:

`map.setInitialViewpoint(viewpoint);`

**Comment by minakshibh** [comment]
map.setInitialViewpoint(viewpoint) works even after the setMap() method call.

Thanks for the help.
