### ISSUE TITLE
Identify on map image layers identifyLayerResult.getElements() always is Emptry?

### ISSUE THREAD

**Issue by yinxh2016** [Esri/arcgis-runtime-samples-android#555]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by TADraeseke** [comment]
Is this for a specific sample? Can you provide your code please?
