### ISSUE TITLE
why the map didn't show

### ISSUE THREAD

**Issue by montezwl** [Esri/arcgis-runtime-samples-android#561]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

I did as the first sample of ArcGIS Runtime ArcGIS Runtime SDK for Android, display a map. but the map did not show as the sample guide. what's wrong? 
the guide say "If the app runs but the map is blank, then check that the android.permission.INTERNET permission was correctly added to the Android manifest."  i'm very sure i add the code <uses-permission android:name="android.permission.INTERNET" /> in the manifest. but it didn't work.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by TADraeseke** [comment]
Hi @montezwl - Did you manage to resolve this? 

If not, are you sure the device had internet access at the time? Could you provide a stack trace of any error please?

Thanks!
