### ISSUE TITLE
A build problem

### ISSUE THREAD

**Issue by TomorrowDreamer** [Esri/arcgis-runtime-samples-android#573]
I integrate map into my project by "https://developers.arcgis.com/labs/android/create-a-starter-app/" 
but when i run the project  ,the process stop,and  show below:

Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
Message{kind=ERROR, text=Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?, sources=[F:\project\*********\build\intermediates\res\merged\debug\values-ar\values-ar.xml:67], original message=, tool name=Optional.of(AAPT)}

how could i resolve this problem?

**Comment by LDuncAndroid** [comment]
Hi @TomorrowDreamer,

It appears that potentially one of your strings has multiple formatting placeholders without the necessary positional attributes.

https://developer.android.com/guide/topics/resources/string-resource#formatting-strings

Can you provide a link to your repo? Or a .zip containing your project?
