### ISSUE TITLE
GeoPackage failed to load!

### ISSUE THREAD

**Issue by sunshine0576** [Esri/arcgis-runtime-samples-android#587]
Version 100.4 
arcgis-runtime-samples-android/java/feature-layer-geopackage/

When I tried to use my own data, I made a mistake.
It is produced with QGIS，can open by "ngageoint/geopackage-android"

[test.zip](https://github.com/Esri/arcgis-runtime-samples-android/files/2883436/test.zip)

GeoPackage failed to load!com.esri.arcgisruntime.ArcGISRuntimeException: Unable to open the database file

**Comment by LDuncAndroid** [comment]
Hi @sunshine0576 , 

Can you double check the provided `.zip` file? I am having trouble unzipping it.

Thanks.
