### ISSUE TITLE
Not able to build the sample app

### ISSUE THREAD

**Issue by rajivjam** [Esri/arcgis-runtime-samples-android#59]
I have downloaded latest sample app from github. 
I am using below dependencies:
 repositories {
        jcenter()
        maven {
            url 'http://dl.bintray.com/esri/arcgis'
        }
    }

	dependencies {
    	compile 'com.esri.arcgis.android:arcgis-android:10.2.6-2'
	}

I tried to build the app and getting following error.

D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\AddCSV2GraphicsLayer\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\AttributeEditor\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\Basemaps\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\BasicLicense\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\ClassBreaksRenderer\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\ClosestFacilities\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\Convert2MGRSGrid\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\CreateRuntimeGeodatabase\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\DynamicLayerRenderer\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\ExportTileCacheTask\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\FeatureServiceTableQuery\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\FeatureUserGroup\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\FragmentManagement\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\GeoJSONEarthquakeMap\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\GeometryEditor\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\GeometrySample\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\HelloWorld\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\IdentifyTask\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\LocalMBTiles\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\LocalRasterData\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\MapLegend\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\MapRotation\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\Measure\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\MilSym2525c\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\Nearby\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\OAuth2\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\OfflineAnalysis\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\OfflineEditor\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\OfflineRoutingAndGeocoding\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\PlaceSearch\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\PopupInWebMapForEditing\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\PopupInWebMapForViewing\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\PopupUICustomization\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\QueryCloudFeatureService\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\QueryTask\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\Routing\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\ServiceArea\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\SimpleMap\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\StandardLicense\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\StandardLicenseOffline\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\SwitchMaps\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\UniqueValueRenderer\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\ViewShed\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>
D:\Work\Android\TLWorkSpace\AirportIndoorNavigation\ArcSDK\SAmple\arcgis-runtime-samples-android-master\WmsLayer\build.gradle
Error:Failed to find: com.esri.arcgis.android:arcgis-android:10.2.6-2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>

**Comment by doneill** [comment]
@rajivjam When you say you downloaded, does that mean you downloaded the zip file?  It does not look like you forked the repo.  How did you import the project into Android Studio?  I just went through the following steps and could not reproduce your issue:  

- Cleared my gradle cache.  I did this to ensure I was not using our sdk from a cache on my local disk
- Downloaded the samples, from [here](https://github.com/Esri/arcgis-runtime-samples-android/archive/master.zip)
- Opened the downloaded zip archive to a location on my local disk
- Selected **Import project (Eclipse ADT, Gradle, etc.)** from the **Quick Start** menu. 
- Once project is imported, **Sync Project with Gradle Files**.  This downloads the *.aar lib module.  

At this point I can run any sample.  Is this the workflow you went through?  

You could also fork the repo and then clone it locally to better stay in sync with any changes to our samples repository.  Instructions for that are [here](https://github.com/Esri/arcgis-runtime-samples-android/blob/master/README.md).

Please list your workflow if you continue to have issues and/or did something differently.

**Comment by rajivjam** [comment]
Thanks for the support @doneill. I upgraded my Android Studio and it downloaded required files.
Thanks
Rajiv
