### ISSUE TITLE
turn off map rotation

### ISSUE THREAD

**Issue by xleix** [Esri/arcgis-runtime-samples-android#604]

**Comment by TADraeseke** [comment]
Hi tleix,

We encourage everyone to collaborate on questions like this on [GeoNet ArcGIS runtime SDK](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android). So please post any follow up questions there.

Short answer to your question, override the onRotate touch event in the `DefaultMapViewOnTouchListener` like this:

```
    mMapView.setOnTouchListener(new DefaultMapViewOnTouchListener(this, mMapView)  {
      @Override public boolean onRotate(MotionEvent event, double rotationAngle) {
        return true;
      }
    });
```

Good luck with your app!
Trevor
