### ISSUE TITLE
Route between two Points

### ISSUE THREAD

**Issue by rajivjam** [Esri/arcgis-runtime-samples-android#61]
Hi,

I am able to load the map using the sdk. I need to show route between two points based on lat and Long. I have route service url, but I dont know how to call RouteTask service with two points
Is there any sample code available for this?

Thanks 
Rajiv

**Comment by doneill** [comment]
@rajivjam Please look at our Routing sample for point to point routing using the ```RouteTask```.  If you have any questions about our routing API please use our [GeoNet forums](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android).  Please do not hesitate to create issues here with any specific samples where you find issues with the sample , need more specific information related to a specific sample sub module, or need assistance getting the samples repository working in your local developer environment.

**Comment by rajivjam** [comment]
@Doneill: I am able to show the routemap between two points using ArcGIS sdk.

Thanks

**Comment by doneill** [comment]
:+1:
