### ISSUE TITLE
android 4.4.2   使用100.4 加载geodatabase文件时 如果路径含有中文 无法读取内部数据

### ISSUE THREAD

**Issue by ljk761626336** [Esri/arcgis-runtime-samples-android#616]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changanxian** [comment]
你的问题正在调研， 请以后使用 https://community.esri.com/ 网站报告问题， 谢谢！

**Comment by liangchenxijin** [comment]
Arcgis for android 10.2.9如何加载geosever生成的geoserver-dispatch.application矢量数据？

**Comment by ljk761626336** [comment]
没有做过&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liangchenxijin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 晚上6:38
收件人:&nbsp;"Esri/arcgis-runtime-samples-android"<arcgis-runtime-samples-android@noreply.github.com&gt;;
抄送:&nbsp;"雪落无声"<761626336@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Esri/arcgis-runtime-samples-android] android 4.4.2   使用100.4 加载geodatabase文件时 如果路径含有中文 无法读取内部数据 (#616)




Arcgis for android 10.2.9如何加载geosever生成的geoserver-dispatch.application矢量数据？
