### ISSUE TITLE
Call method unselectFeatures() Exception

### ISSUE THREAD

**Issue by xleix** [Esri/arcgis-runtime-samples-android#618]
Each time `featureLayer.unselectFeatures(selectFrature)` is called, an error is reported, and both `featureLayer` and `selectFrature` are not null.
in sdk 100.3
Thank you very much for taking the time to pay attention to this issue.

![image](https://user-images.githubusercontent.com/18733388/56560657-9ee9b080-65d7-11e9-80e0-cb9ebf5e7920.png)

**Comment by mbcoder** [comment]
Hi,

Sorry for the late response.  If you are still experiencing issues with your app code, then you should post your question in the following forum https://github.com/Esri/arcgis-runtime-samples-android/issues/598

This repository is for issues related to the sample code only.
