### ISSUE TITLE
多个geodatebase在fragment中添加，全部都加载成功，可以查询，但有时候会有其中一两个图层在地图上不显示

### ISSUE THREAD

**Issue by yinxh2016** [Esri/arcgis-runtime-samples-android#643]
![IMG_4547](https://user-images.githubusercontent.com/21007043/63006300-d21abd00-beb0-11e9-9f2e-13bbacc6bf8f.JPG)

**Comment by changanxian** [comment]
@yinxh2016  以后请使用这个网站报告bug: https://community.esri.com/
Since we don't have enough info for your problem,  here is only my guess: is it possible that the feature layers are scale-dependent?  Please detail the steps to repo your issue, and include data if possible.
