### ISSUE TITLE
the click listener for points of  geodatabase . 

### ISSUE THREAD

**Issue by mybobo1213** [Esri/arcgis-runtime-samples-android#646]
first , the version of arcgis for android is 100.5 . have a geodatabase file in local.  
Different versions vary greatly(10.x to 100.5). I want to know how to get click events and corresponding data . Hope to give some advice.

At present, there is little information about the new version.Please recommend some knowledge websites or information. I am very grateful for your reply.

**Comment by mbcoder** [comment]
@mybobo1213 10.x is a very old version of the SDK and was replaced by the 100.x series a few years ago.

All documentation can be found here:  https://developers.arcgis.com/android/latest/guide/guide.htm

You don't say much about your application but you may want to look at identify operations to get information about items on your map:

https://developers.arcgis.com/android/latest/guide/identify-features.htm

This git repository also contains a number of working samples to help you get going.

If you have general questions like this, then please post your questions on the GeoNet forum.

https://developers.arcgis.com/android/support/

This git repro is for issues related to the sample code.

**Comment by mybobo1213** [comment]
Thank you for your reply. I have a new question about loading online Golden Maps and Google Maps. Find a lot of information found that the effect is not very good, the official documents did not notice this knowledge, please give some suggestions, I am grateful. I am a beginner, and many things are being understood. My platform is Android. I look forward to your reply very much. Have a good time.

**Comment by mbcoder** [comment]
For loading different basemap types, you should look at this sample:

https://github.com/Esri/arcgis-runtime-samples-android/blob/master/java/change-basemaps/src/main/java/com/esri/arcgisruntime/sample/switchbasemaps/MainActivity.java

The specific API for this can be found here:

https://developers.arcgis.com/java/latest/api-reference/reference/com/esri/arcgisruntime/mapping/Basemap.html#%3Cinit%3E()

If you have general questions like this, then please post your questions on the GeoNet forum.

https://developers.arcgis.com/android/support/

This git repro is for issues related to the sample code.

I think your question has been translated from another language.  If the message isn't coming across then you could try asking in your own language.
