### ISSUE TITLE
How can i add marker like google map and popWindow 

### ISSUE THREAD

**Issue by mehulTank** [Esri/arcgis-runtime-samples-android#652]
arcgis team , 
i  have go through this demo it is good but i have some query  how can i add marker like google map and it's popwindow. i have seen in example here is point but other query is how can i get point here is given all static point i want to draw path which user selected location from a to b.
is there any option for that ?

**Comment by TADraeseke** [comment]
Hello!

We try to use this repo specifically for the maintenance of the samples. For questions like this, please post on [GeoNet](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android/content). There you'll be able to work with other Runtime users and developers.

Thanks!

**Comment by mehulTank** [comment]
Thanks For your response i have posted question on your given above link but no any response on that other think is how can i add marker via latitude and longitude 


![image](https://user-images.githubusercontent.com/15247268/65659803-76645780-e04a-11e9-9dfc-5af6b75c170d.png)

**Comment by mbcoder** [comment]
I've just posted a reply, so closing this issue.

https://community.esri.com/thread/240697-how-can-i-add-marker-like-google-map-and-popwindow
