### ISSUE TITLE
Bug - missing Sample Code sction - Display scene in tabletop AR

### ISSUE THREAD

**Issue by markjdugger** [Esri/arcgis-runtime-samples-android#657]
## Bug

Source code is missing from **Display scene in tabletop AR** samples.

##  Behavior
1 Go to this page: https://master-stage.developers.arcgis.com/android/latest/java/sample-code/display-scene-in-tabletop-ar/
2 Notice that Sample Code section is empty.

## To fix:
Change the json metadata file from this:
```
"snippets": [
        "src/main/java/com/esri/arcgisruntime/displaytabletopmapinar/MainActivity.java"
    ],
```

to
```
"snippets": [
        "src/main/java/com/esri/arcgisruntime/displaysceneintabletopar/MainActivity.java"
    ],
```

**Comment by TADraeseke** [comment]
Thanks for spotting this @markjdugger! This was my fault as a result of the name of the sample changing. I've fixed this in the samples repo now, could you verify on the next build of the webpage? Thanks!

**Comment by markjdugger** [comment]
Fix is now visible on public dev web site:
https://developers.arcgis.com/android/latest/java/sample-code/display-scene-in-tabletop-ar/

Closing this bug as fixed.
