### ISSUE TITLE
App crashes on when running on Huawei Y5

### ISSUE THREAD

**Issue by cuongl** [Esri/arcgis-runtime-samples-android#661]
# The app throws RuntimeException: createContext failed: EGL_SUCCESS

##  Behavior

the app throws RuntimeException: createContext failed: EGL_SUCCESS

## Steps to Reproduce

Install the app on on Huawei Y5

1. run the app
2. app will crash

10-17 17:51:20.521 E/AndroidRuntime(21908): java.lang.RuntimeException: createContext failed: EGL_SUCCESS
10-17 17:51:20.521 E/AndroidRuntime(21908): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1232)
10-17 17:51:20.521 E/AndroidRuntime(21908): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1223)
10-17 17:51:20.521 E/AndroidRuntime(21908): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1073)
10-17 17:51:20.521 E/AndroidRuntime(21908): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1440)
10-17 17:51:20.521 E/AndroidRuntime(21908): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)

**Comment by TADraeseke** [comment]
Hello! 

Can you give some more details on this? Which sample are you running and what are you doing with the sample when it crashes?

The stack trace doesn't appear to be referencing any parts of ArcGISRuntime explicitly.

Thanks!
Trevor

**Comment by cuongl** [comment]
click on "analysis" and "analyse hotspots". I know there is no reference to the ArcGISRuntime explicitly but it happens when ArcGISRuntime is initialised. Does any one know how to handle this crash?

**Comment by gunt0001** [comment]
@cuongl - there is no way to handle this crash on your end. It's likely an issue with the specific device hardware. Can you share more info on this specific device (Huawei Y5)? I.e. from which year is it, Android version, CPU spec, GPU spec. Thank you!

**Comment by cuongl** [comment]
https://consumer.huawei.com/au/phones/y5-2019/specs/

**Comment by javadghane** [comment]
@gunt0001 @TADraeseke  look like [this issue ](https://github.com/Esri/arcgis-runtime-samples-android/issues/456 ).
