### ISSUE TITLE
Error inflating class com.esri.arcgisruntime.toolkit.ar.ArcGISArView

### ISSUE THREAD

**Issue by CraZyLegenD** [Esri/arcgis-runtime-samples-android#666]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Feature or Bug?

 Error inflating class com.esri.arcgisruntime.toolkit.ar.ArcGISArView

##  Behavior

   implementation 'com.esri.arcgisruntime:arcgis-android-toolkit:100.6.0'
    implementation 'com.esri.arcgisruntime:arcgis-android:100.6.0'

## Steps to Reproduce

1. Open a new project
2. Include the dependencies
`   implementation 'com.esri.arcgisruntime:arcgis-android-toolkit:100.6.0'
    implementation 'com.esri.arcgisruntime:arcgis-android:100.6.0'`

3. Activity main layout file has only root 
`<?xml version="1.0" encoding="utf-8"?>
<com.esri.arcgisruntime.toolkit.ar.ArcGISArView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/arView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity" />`

`    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.arcgisar/com.example.arcgisar.MainActivity}: android.view.InflateException: Binary XML file line #2 in com.example.arcgisar:layout/activity_main: Binary XML file line #2 in com.example.arcgisar:layout/activity_main: Error inflating class com.esri.arcgisruntime.toolkit.ar.ArcGISArView
`

`2019-11-06 11:28:54.638 8293-8293/com.example.arcgisar E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.arcgisar-PZ-twPgYjScsFHDvcwDWvA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.arcgisar-PZ-twPgYjScsFHDvcwDWvA==/lib/x86_64, /data/app/com.example.arcgisar-PZ-twPgYjScsFHDvcwDWvA==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libc++_shared.so"`

**Comment by CraZyLegenD** [comment]
Same thing happens using this link

**Comment by CraZyLegenD** [comment]
I don't encounter this error on an emulator x86 architecture but using x86_64 it crashes

**Comment by mbcoder** [comment]
We currently don't support x86-64 emulator architectures.  For the best development experience you should be using physical devices which will be ARM based.  We support 32 and 64bit for these.

**Comment by CraZyLegenD** [comment]
Thanks, I'll be closing the issue now.
