### ISSUE TITLE
offline use updateFeatureAsync(Feature feature) ,somtime there's a mistake of The database disk image is malformed

### ISSUE THREAD

**Issue by zhm971244310** [Esri/arcgis-runtime-samples-android#674]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by TADraeseke** [comment]
Hi!

We try to use this repo just to track issues with our samples. Is this behaviour from a specific sample or is this from your own project? If it's from your own project, try using [GeoNet](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions.

Cheers,
Trevor
