### ISSUE TITLE
getAttributes and getAttributeNames returns alphabetical ordered values

### ISSUE THREAD

**Issue by salihyalcin** [Esri/arcgis-runtime-samples-android#68]
When using Graphic component of SDK, getAttributes and getAttributeNames returns alphabetical  ordered information. When someone want to use attributes hierarchical, it is not possible. 

For handling this issue , I used outfields like this and I want to show my fields order like below;

{Building_Road, Building_ID,Building_Name}

But QueryTask result return like this - (alphabetical);

{Building_ID, Building_Name, Building_Road}

**Comment by salihyalcin** [comment]
After some searches, It showed that this issue occure when adding Graphic to GraphicsLayer.

For example;

queryGraphic = new Graphic(featureGeometry, simpleMarkerSymbole, featureAttrValues);
GraphicsLayer mGraphicsLayer = new GraphicsLayer();
mGraphicsLayer.addGraphic(queryGraphic ); ---> This line make "queryGraphic.getAttributes" values alphabetically ordered. 

MapView.addLayer(mGraphicsLayer);

**Comment by doneill** [comment]
@salihyalcin We do not guarantee the order of attributes from a `Graphic`.  Are you still seeing this behavior? If so, I will look into it deeper.
