### ISSUE TITLE
关于Arcgis加载geoserver生成的application数据加载

### ISSUE THREAD

**Issue by liangchenxijin** [Esri/arcgis-runtime-samples-android#706]
# ArcGIS Android Issue Template
你好Arcgis：

英文不是很好，请谅解！

问题：geoserver生成的application格式数据没找到加载的方法？是否提供方法或解决方案？

非常感谢！
Best Regards
GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by liangchenxijin** [comment]
Behavior

**Comment by XuemingRocks** [comment]
尊敬的用户，

你好！请问你的数据是那些格式？目前我们支持加载WMTS,  WFS, KML 等相关格式，下面是有关api参考和例子的链接：

https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/layers/WmtsLayer.html
https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/ogc/wfs/WfsFeatureTable.html
https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/layers/KmlLayer.html

https://github.com/Esri/arcgis-runtime-samples-android/tree/master/kotlin/wmts-layer
https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/wmts-layer
https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/display-wfs-layer
https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/browse-wfs-layers
https://github.com/Esri/arcgis-runtime-samples-android/tree/master/kotlin/display-kml

又及，和我们的sdk例子相关的问题请在github问，其它的问题请在我们的[GeoNet 论坛](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) 问。谢谢！

**Comment by liangchenxijin** [comment]
http://117.39.60.222:8081/geoserver/gwc/demo/contourService:ankang?gridSet=EPSG:4326&format=application/vnd.mapbox-vector-tile
这个链接打开可以看到这个源数据，请问这个怎么加载？

**Comment by XuemingRocks** [comment]
你可以通过ArcGISVectorTiledLayer(String dataSourceUri)来加载，dataSourceUri应该指向你的应用的MapBox Style。以下是api的说明和一个简单的例子。

https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/layers/ArcGISVectorTiledLayer.html#%3Cinit%3E(java.lang.String)
https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/arcgis-vectortiledlayer-url

**Comment by liangchenxijin** [comment]
第一：我按照上面的方法把这个地址http://117.39.60.222:8081/geoserver/gwc/demo/contourService:ankang?gridSet=EPSG:4326&format=application/vnd.mapbox-vector-tile，但是还是加载不出来，不知道在如何解决？能有其他示例么？
第二：ArcServer可以发矢量切片么？我把以上数据部署到ArcServer上可以加载出来么？

**Comment by XuemingRocks** [comment]
我们sdk 当前支持的MapBox Style 可以参看[这个例子]( http://www.arcgis.com/sharing/rest/content/items/5ad3948260a147a993ef4865e3fad476/resources/styles/root.json)。抱歉，我们目前对GeoServer应用的了解有限，至于如何从你的GeoServer应用得到类似的MapBox Style请与GeoServer联系。

> 第二：ArcServer可以发矢量切片么？我把以上数据部署到ArcServer上可以加载出来么？

这是另外一个合理的方案。ArcGISServer支持发布矢量数据，具体步骤和要求可以参看[这个文档](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/vector-tile-services.htm)。相关问题可以在[这个GeoNet论坛](https://community.esri.com/community/gis/enterprise-gis/arcgis-enterprise)提问。

**Comment by liangchenxijin** [comment]
你好，关于ArcgisServer有试用版的工具么？我们想尝试做一点数据，测试一下，谢谢

**Comment by XuemingRocks** [comment]
> 关于ArcgisServer有试用版的工具么？

这个需要和你当地的经销商联系，每个经销商有不同的策略和模式。你可以试试在ArcGIS Online 上注册一个账号，然后有21天的免费使用Online的功能，更多的信息可以参见[Free Trial](https://www.esri.com/en-us/arcgis/trial)。Online的一些功能包括可以在Online 上发布数据和图层，其中包括矢量数据。若你有格式为.vtpk矢量包，就可以直接在Online上发布图层并和别人分享。
