### ISSUE TITLE
关于#706问题回复，application格式的矢量数据，下面是链接

### ISSUE THREAD

**Issue by liangchenxijin** [Esri/arcgis-runtime-samples-android#710]
http://117.39.60.222:8081/geoserver/gwc/demo/contourService:ankang?gridSet=EPSG:4326&format=application/vnd.mapbox-vector-tile
这个链接打开可以看到这个源数据，请问这个怎么加载？

备注：论坛上链接不了，不知道是什么原因，只能这样提问，谢谢！

_Originally posted by @liangchenxijin in https://github.com/Esri/arcgis-runtime-samples-android/issues/706#issuecomment-588554794_

**Comment by XuemingRocks** [comment]
请参见#706.

Duplicate of #706. Closing ...
