### ISSUE TITLE
When I use TextSymbol,It can not support the Chinese.

### ISSUE THREAD

**Issue by fengleige131** [Esri/arcgis-runtime-samples-android#76]
When I use TextSymbol,It can not support the Chinese.   textSymbol.setFontFamily("DroidSansFallback.ttf"); this can support Chinese; but the android system5.0.2  can use this support number and English.

**Comment by XuemingRocks** [comment]
@fengleige131 textSymbol.setFontFamily("DroidSansFallback.ttf") doesn't works on Android 5.0+ but works on Android ICS and Jellybean. You can try on those Android versions.

It is a known issue. And we are investigating this issue. Thank you for pointing it out.

**Comment by fengleige131** [comment]
OK,thank you for your reply. When you have the solution for this question, please tell me.

**Comment by doneill** [comment]
@fengleige131 Thanks for bringing this to our attention, since this is not an issue tied directly to a sample you should ask this question on GeoNet to share more broadly with our developer community.

**Comment by fengleige131** [comment]
ok,I will do this.
