### ISSUE TITLE
Quartz Samples: Draw mode icon out of sync

### ISSUE THREAD

**Issue by n8ebel** [Esri/arcgis-runtime-samples-android#78]
While drawing, if user taps draw mode icon again (rather than long press) the drawing finishes, but when they tap the icon again, it doesn't enter selected state and is unclear if drawing mode was activated.

Repro steps:

1. tap point icon to enter point drawing mode
2. tap to draw point
3. tap point icon again.  The drawing will finish correctly
4. tap point icon again to enter point drawing mode.  The icon will not be selected, but user can still draw

**Comment by doneill** [comment]
@n8ebel Good Catch!  Thanks for creating this issue and creating a PR #79, I will review.

**Comment by doneill** [comment]
Verified fixed
