### ISSUE TITLE
Quartz Samples: single tap not registering

### ISSUE THREAD

**Issue by n8ebel** [Esri/arcgis-runtime-samples-android#80]
While using the Map Sketching sample I noticed many of my taps never seemed to register.  When I first noticed I thought maybe drawing mode wasn't correctly activated or drawing was just broken, but after debugging it seems it's an issue with the length of the tap.

My natural tap duration (while first using app) only seemed to result in `onSingleTapConfirmed` being called about 1/4 of the time.  After noticing that faster taps were more successful, I'm able to tap more quickly and register the tap more consistently but it still fails enough to require a conscious effort to tap quickly.

Looking at the doc, it seems like this could be related to `TAP_TIMEOUT`, but it doesn't appear that you can change this while making use of `DefaultMapViewOnTouchListener`.

**Comment by doneill** [comment]
What **Android Version** are you using?  Seems the duration for a single tap changed in ICS (4.04) to JellyBean (4.1.x) and above.  ICS uses 125ms for a single tap and JellyBean+ uses 64ms for a single tap.

**Comment by doneill** [comment]
@n8ebel We are investigating our implementation and will follow up on our findings.

**Comment by n8ebel** [comment]
@doneill  I apologize for the VERY delayed comment.  I just noticed the notification for this.  If it still helps I was running on Lollipop.

**Comment by doneill** [comment]
@n8ebel We are just using the `TAP_TIMEOUT` valued defined by the Android OS. I will look to reporting the issue to Google.

**Comment by doneill** [comment]
@n8ebel We provided a fix for this with beta-3, can you verify it works for you?

**Comment by doneill** [comment]
I am closing as verified.  @n8ebel Please update the issue if you continue to have issues.
