### ISSUE TITLE
Esri VectorTiledLayer refresh problem 

### ISSUE THREAD

**Issue by teomanyaman** [Esri/arcgis-runtime-samples-android#843]
```
myVectorLayer = AGSArcGISVectorTiledLayer(url: url!) 
if let rc = AGSRequestConfiguration.global().copy() as? AGSRequestConfiguration {
    rc.requestCachePolicy = .reloadIgnoringLocalAndRemoteCacheData
    rc.shouldCacheResponse = false
    myVectorLayer?.requestConfiguration = rc
}
self.mapView.map?.operationalLayers.add(myVectorLayer!)
```

Hi
There is such a solution on the ios side
Our equivalent to RequestConfiguration but I couldn't find the process of canceling cache

**Comment by TADraeseke** [comment]
Hi @teomanyaman - This looks like swift and I think you're therefore best asking the question the ArcGIS Runtime iOS GeoNet forum found here: https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios

**Comment by ikbalyasar** [comment]
Hi TADraeseke,
What is the equivalent of this code in the Android SDK?

**Comment by nixta** [comment]
Hi @ikbalyasar. Are you serving these tiles from ArcGIS Enterprise? If you have access to the server to configure it, you could add an outgoing header.

The Android SDK honors `Cache-Control: no-cache` or `Cache-Control: max-age=<seconds>` which could ensure that tiles are not cached and are always requested.
