### ISSUE TITLE
Navigate Route sample (kotlin)

### ISSUE THREAD

**Issue by markdeaton** [Esri/arcgis-runtime-samples-android#857]
## Feature or Bug?

This is one bug and one deprecation fix.

##  Behavior

Both issues pertain to [this file](https://github.com/Esri/arcgis-runtime-samples-android/blob/master/kotlin/navigate-route/src/main/java/com/esri/arcgisruntime/sample/navigateroute/MainActivity.kt)

1. Lines 103, 104 invoke a route solve async operation, but then listen to the routeParameterFuture. Line 104 should probably reference routeResultFuture instead of routeParametersFuture.
Also, [line 94](https://github.com/Esri/arcgis-runtime-samples-android/blob/304e6a35ec2212d6276369f032b5dd31623b7ef5/kotlin/navigate-route/src/main/java/com/esri/arcgisruntime/sample/navigateroute/MainActivity.kt#L94) should probably mention parameters, rather than the route; likewise, [line 133](https://github.com/Esri/arcgis-runtime-samples-android/blob/304e6a35ec2212d6276369f032b5dd31623b7ef5/kotlin/navigate-route/src/main/java/com/esri/arcgisruntime/sample/navigateroute/MainActivity.kt#L133) should probably report an error with the route, instead of the parameters.

2. Lines 73-74 reference Resources.getSystem().configuration.locale, but this is deprecated in the later Android SDKs. It should probably be Resources.getSystem().configuration.locales[0] instead (See [Android docs](https://developer.android.com/reference/android/content/res/Configuration?hl=en#locale).)

## Steps to Reproduce

N/A

**Comment by TADraeseke** [comment]
Thanks @markdeaton! I've put in fixes for point 1. Point 2 we can't support yet as our min SDK is 21. `locales[0]` is supported in API 24 and higher only.
