### ISSUE TITLE
RelatedFeatureQueryResult not working

### ISSUE THREAD

**Issue by minakshibh** [Esri/arcgis-runtime-samples-android#861]
I have follow the same example as you have mentioned into sample code but this query is not working for android.

 **// Fetch the related features from the selected feature.
                    RelatedQueryParameters parameters = new RelatedQueryParameters(info);
 ListenableFuture<List<RelatedFeatureQueryResult>> relatedFeatureQueryResultFuture = selectedTable   .queryRelatedFeaturesAsync(arcGISFeature, parameters);
                    relatedFeatureQueryResultFuture.addDoneListener(() -> {
                        mProgressBar.setVisibility(View.GONE);
                        try {
                            relatedFeatureQueryResultFuture.get().forEach(result -> {
                                if (result.getFeature() instanceof ArcGISFeature) {
                                    ArcGISFeature returnedFeature = result.getFeature();
                                    // Load the related feature to bring in all field values
                                    returnedFeature.loadAsync();
                                    // .. Process each returned feature for this hydrant ..
                                }
                            });
                        } catch (ExecutionException | InterruptedException e) {
                            // .. handle any exception that may occur
                        }

**Comment by TADraeseke** [comment]
Can you link to the sample in question? I'm guessing you're also using your own data? Can you share that too? Thanks!
