### ISSUE TITLE
Geocoding uses depreceated http instead of https

### ISSUE THREAD

**Issue by Syn-crow** [Esri/arcgis-runtime-samples-android#863]
## Bug
The url for the search can't be reached, url should use https instead of the current http

##  Behavior
error is displayed

## Steps to Reproduce
type anything in search bar

## Fix
Find address sample, line 91 
    mLocatorTask = new LocatorTask("http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer");
       =>     mLocatorTask = new LocatorTask("https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer");

**Comment by TADraeseke** [comment]
Thanks @Syn-crow!

**Comment by TADraeseke** [comment]
Just merged in a fix for http -> https across all the samples. Thanks again!
