### ISSUE TITLE
Quartz Design Mode Rendering

### ISSUE THREAD

**Issue by snodnipper** [Esri/arcgis-runtime-samples-android#89]
It would be great if we could still see our designs when a MapView is added.  I totally accept this is not an issue with the quartz samples per se.  Perhaps issues should not be raised whatsoever for quartz?

<img width="795" alt="screen shot 2015-10-01 at 10 37 27" src="https://cloud.githubusercontent.com/assets/576719/10217548/7d079186-6828-11e5-8e73-20beb5ba2471.png">

**Comment by shellygill** [comment]
Thanks for reporting this @snodnipper. For reporting issues specifically with the beta release of the SDK, you can use the forums in the Early Adopter community to report issues. If you are not already a member, just go to the [Beta SDK homepage](https://developers.arcgis.com/android/beta/) and click on the 'Join the beta' button, and follow the instructions there... Once you are signed up and logged in to the Early Adopter community site, then look for Project Resources -> User Forums on the left of the page. 

However, there's no need to report this one - we already have an internal issue in progress for this specific problem.

**Comment by shellygill** [comment]
Note to update https://github.com/Esri/arcgis-runtime-samples-android/issues/89 to indicate when this fix will be available.

**Comment by doneill** [comment]
Closing as Known Issue.
