### ISSUE TITLE
getFields and getField(String fieldName) always returning null when using FeatureLayer in Method

### ISSUE THREAD

**Issue by salihyalcin** [Esri/arcgis-runtime-samples-android#92]
When using ArcGISFeatureLayer in method to make some stuff, ArcGISFeatureLayers  getField(String fieldname) and getFields() methods are always returning null.

It only works when debug mode... 

Sample usage;

    public static Map getCodedDomainNames(String featureLayerLink, UserCredentials userCredentials, final String fieldAliasName) {

        final ArcGISFeatureLayer codedValueFeatureLayer = new ArcGISFeatureLayer(featureLayerLink, ArcGISFeatureLayer.MODE.SNAPSHOT, userCredentials);
        final CodedValueDomain[] cvd = new CodedValueDomain[1];     

        Field field = codedValueFeatureLayer.getField(fieldAliasName);
        if (field.getDomain() instanceof CodedValueDomain) {
            cvd[0] = (CodedValueDomain) field.getDomain();

        }

        return cvd[0].getCodedValues();
    }

**Comment by doneill** [comment]
@salihyalcin Which sample are you referring to?
