### ISSUE TITLE
Error inflating class com.esri.arcgisruntime.mapping.view.SceneView 如何解决呢

### ISSUE THREAD

**Issue by feng55** [Esri/arcgis-runtime-samples-android#941]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".Arcgis3DMapActivity">

    <com.esri.arcgisruntime.mapping.view.SceneView
        android:id="@+id/sceneView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</LinearLayout>

**Comment by TADraeseke** [comment]
Hello! Please post all general questions here: https://community.esri.com/t5/arcgis-runtime-sdk-for-android-questions/bd-p/arcgis-runtime-sdk-for-android-questions

We try to keep this repo just for issues specific to the samples contained within.
