### ISSUE TITLE
error: Shapefile feature table failed to load

### ISSUE THREAD

**Issue by ozzyzhou99** [Esri/arcgis-runtime-samples-android#983]
# Shapefile feature table failed to load

When I run the project in Android Studio, the error in logcat is as follows：

2022-05-21 15:41:18.545 19470-19470/com.example.tianditutest E/MainActivity: Shapefile feature table failed to load: com.esri.arcgisruntime.ArcGISRuntimeException: Unknown error.: Shape file not found: /storage/emulated/0/Download/JL_GZW_A.shp

The SDK version I use is com.esri.arcgisruntime:arcgis-android:100.14.0

and I‘ve allowed reading from local storage in your manifest file.

**Comment by TADraeseke** [comment]
Looks like you're using your own data.

Google's made it really hard to read local data from a location outside of the app's scoped storage in the last few years.

You'll notice in our sample the user's being directed to put their local data into the app's local storage, not a download folder.

https://github.com/Esri/arcgis-runtime-samples-android/tree/main/java/feature-layer-shapefile#offline-data
