### ISSUE TITLE
Offline Routing example project throwing an error

### ISSUE THREAD

**Issue by tashi146** [Esri/arcgis-runtime-samples-android#985]
# ArcGIS Android Issue with Offline Routing

I have used the Kotlin Offline Routing project and added the files in the required folder. But When I run the app I am getting 
"Error Loading route task: Not found.".   
I can see the map and pin as well. But route path is not drawing.

https://github.com/Esri/arcgis-runtime-samples-android/tree/main/kotlin/offline-routing

This is how I am loading: `val tileCache = TileCache(filesDir.path + getString(R.string.tpkx_path))`

This is the file path:   

![image](https://user-images.githubusercontent.com/106508204/172842198-70483e65-9318-43d1-abaa-229782587a7a.png)

<img src="https://user-images.githubusercontent.com/106508204/172626224-1f255e6b-8713-4368-81c1-ee1a75a04155.jpg" width="350" height="700" />

**Comment by TADraeseke** [comment]
Could be because one of the two pins is in the water and not near a transport network. Can you try two points on land?

**Comment by tashi146** [comment]
No, Still it doesn't work. When I run the app I get a toast message saying "Error Loading route task: Not found".    
I have both `sandiego.geodatabase `and `streetmap_SD.tpkx` in `/Android/data/com.esri.arcgisruntime.sample.offlinerouting/files` path

**Comment by shubham7109** [comment]
You will need the `sandiego.tn/` ([download](https://arcgisruntime.maps.arcgis.com/home/item.html?id=df193653ed39449195af0c9725701dca)) folder along with `streetmap_SD.tpkx` and `sandiego.geodatabase` to run the sample. It contains the street schema files to calculate the routing. We will create an issue to update the README file to address this issue

**Comment by tashi146** [comment]
Ah, I see. Thanks,It is working fine now. You can close this issue as well. One more thing before you go, Sample example are great and helpful but I am having difficult understanding  how this map are created from arcgis online/server. Please provide me steps or tutorial how [this link](https://arcgisruntime.maps.arcgis.com/home/item.html?id=df193653ed39449195af0c9725701dca) are generated because I want to have my own map area to work offline.

Thanks again
