### ISSUE TITLE
Downloaded map list not showing when open the application again

### ISSUE THREAD

**Issue by tashi146** [Esri/arcgis-runtime-samples-android#986]
#Downloaded map list not showing in list.
**Issue**   
I have tried to running the example application for` download-preplanned-map-area` and it is running fine. I am able to download map and display the downloaded map in downloaded list as well. 
But when I close the app and try running again. downloaded map are not listing in downloaded list.   

**Question**   
I can see how we are downloading map with `DownloadPreplannedOfflineMapJob` and load the result. But How can we load the map which is already downloaded in cache folder? 

I am expeting code something similar like this:    
`ArcGISMap offline = ArcGISMap.createFromInternal("")
`   
But I can't get the proper field and parameter.   

_In Screenshot below you can see city hall, and village green are downloaded and download button are disabled as well but not listing in downloaded list when I close and  run the application._
<img src="https://user-images.githubusercontent.com/106508204/172788732-c075a7e4-3c81-430e-a60b-17b639014dbc.jpg" width="350" height="700" />

https://github.com/Esri/arcgis-runtime-samples-android/tree/main/java/download-preplanned-map-area

**Comment by TADraeseke** [comment]
Hi Tashi!

We save the map to the cache in the sample only because we expect people to run it more than once and we need it to effectively be "reset" by the time they run it again.

Instead of saving the map to the cache, save it to the app's scoped storage with `getExternalFilesDir(null)` instead of `cacheDir`

**Comment by tashi146** [comment]
Hi @TADraeseke,
Thanks for quick respond. I am saving in file path only instead of cache and every time I download I can see map data in the file path.   
But when I close and run application again. Downloaded map are not listing in downloaded listview. And I know because there is no logic in code to display map list from file.

_Here is the snippet_
![path](https://user-images.githubusercontent.com/106508204/172861063-843fc275-835b-438c-8a46-8e390374f155.PNG)

**Comment by TADraeseke** [comment]
Hi @tashi146 -- sorry I'm with you now...

So what's being created from the `DownloadPreplannedOfflineMapJob` is a `MobileMapPackage` (.mmpk). In our API a mobile map package on disk can either be `mymap.mmpk` (if it's zipped) or in an exploded state it's a folder. For yours it's `City Hall Area` which contains a `p13` folder and so on. This is a mobile map package too! So...

You can create a `MobileMapPackage(getExternalFilesDir(null)?.path + "/City Hall Area"` (I don't recall the syntax it might need to be City_Hall_Area) and then [set the first map from the mobile map package to `mapView.map` ](https://github.com/Esri/arcgis-runtime-samples-android/blob/main/kotlin/open-mobile-map-package/src/main/java/com/esri/arcgisruntime/sample/openmobilemappackage/MainActivity.kt#L69).

Alternatively if you're in the same app that's run the `DownloadPreplannedOfflineMapJob` you can access the mobile map package at this line by [replacing `downloadPreplannedOfflineMapResult.offlineMap` with `downloadPreplannedOfflineMapResult.mobileMapPackage`](https://github.com/Esri/arcgis-runtime-samples-android/blob/main/kotlin/download-preplanned-map-area/src/main/java/com/esri/arcgisruntime/sample/downloadpreplannedmaparea/MainActivity.kt#L209)

This should get you where you need to be :)

I'd really like to know how good our samples are at supporting our users--what are we getting right? what are we getting wrong? Any chance you'd be interested in a short email or call with me to help me improve our offering by understanding how you're using this stuff? Please drop me an email if so! TDraeseke@esri.com

**Comment by tashi146** [comment]
@TADraeseke Thanks, I will check and let you know
